### ISSUE TITLE
Incorrect work of option "withException" / logger.Error(ex)

### ISSUE THREAD

**Issue by Pyfhon** [NLog/NLog#1034]
Hi
NLog 4.2.0
It seems that message layout renderer always outputs stack trace if "message" parameter has not been set.

Test code:

``` c#
static void Main(string[] args)
{
    LogManager.GetCurrentClassLogger().Error(new Exception("test 1"));
    LogManager.GetCurrentClassLogger().Error(new Exception("test 2"), string.Empty);
}
```

NLog.config:

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <targets>
        <target xsi:type="File" encoding="UTF-8"
            name="File"
            filename="Log.log"
            layout="${message:withException=true} ${exception:format=tostring}" />
    </targets>

    <rules>
        <logger name="*" minlevel="Trace" writeTo="File" />
    </rules>
</nlog>
```

Result with 'withException=false':

```
System.Exception: test 1 System.Exception: test 1
 System.Exception: test 2
```

Result with 'withException=true':

```
System.Exception: test 1
System.Exception: test 1 System.Exception: test 1

System.Exception: test 2 System.Exception: test 2
```

**Comment by 304NotModified** [comment]
I see it. The problem is that:

```c#
Logger.Error(new Exception("test 1"));
```


Should it write to `${message}` or `${exception}`? Well, now it's doing both because it's ambiguous.

**Comment by Pyfhon** [comment]
I think that all the information about exception should write to ${exception} and to ${message} should be written the value of the "Message" parameter

In previous versions, there was no ambiguity as the "message" parameter was the first and it always had to pass (even in the form of "string.Empty"), so now when this parameter is last and empty, I do not see any reason to pass it, and I would expect ${message} is empty. Of course, if this parameter is passed, it will solve the problem, it just looks like a dirty hack.

**Comment by 304NotModified** [comment]
We have the following options regarding calling Log(Exception)

1. Only record the exception to ${exception}
2. Only record the exception to ${message}
3. Doing both
4. Your proposal:  ${exception} and title to  ${message}
5. Configurable

Analysis:

- Some people expect 1, some 2. 
- 1 is analogous with `Log(exception, string)`, 
- 2 is analogous with `Log(object)`.
- I'm not sure about 4, because `Log(object)` also uses `ToString`, and I don't like special cases for `Exception`.

We can make it configurable. But then we need a good default ;) 

What do you think?

**Comment by Pyfhon** [comment]
The problem is that when the option `withException = true` $ {message} output 2 identical message `exception.ToString()`.

To solve this problem, I see two options.
The first - to use a special case for exceptions (not see anything wrong, partly because it is being used as a `logEvent.Exception = ex`).
The second - completely separate calls `Log(exception)` and `Log(object)` in the form of method overloading.

**Comment by 304NotModified** [comment]
> Actually, I do not really understand what is the point of output information about exceptions to ${message}, especially when we have the renderer ${exception} and a single method with a lot of overloads.

Well, to be consistent with `Log(int)` etc

**Comment by Pyfhon** [comment]
1

**Comment by 304NotModified** [comment]
I think we should fix it, but not before 5.0 (breaking change)

**Comment by snakefoot** [comment]
NLog 4.5.4 partially resolves this by correctly capturing Exception-object, when logging as single parameter. Ex:
`logger.Fatal(ex);`
See also: #2586

NLog 4.6 changes `${mesage:withException=true}` to only log the Exception-object a single time. See also #2978

NLog 5.0 changes the default Target Layout to be  `${mesage:withException=true}`. See also  #3637

I would say this issue is very close to resolved. But just missing one last nail to be completely resolved.

**Comment by snakefoot** [comment]
Created PR #3684 as the last nail for the coffin.
