### ISSUE TITLE
Filetarget: remove unneeded conversions from string to byte array / streams

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1075]
FileTarget uses one multiple places conversion from / to byte array. This lead to lower performance, see also https://github.com/NLog/NLog/issues/1071.
## sync steps
1. `FileTarget.Write(LogEventInfo logEvent)`
2. `GetFormattedMessage` (returns `string`)  - nb: the simpleLayout uses a `stringbuilder`
3. `GetBytesToWrite` from `string` to byte[]`
4.  transformed to `byte[]` and written to file appender. A lot of CPU is in this conversion step.
## async steps
1.  `FileTargetWrite(AsyncLogEventInfo[] logEvents)`
2. `GetFormattedMessage` (returns `string`)  - nb: the simpleLayout uses a `stringbuilder`
3. `GetBytesToWrite` from `string` to byte[]`
4.  all messages are written to `MemoryStream` in `FileTargetWrite(AsyncLogEventInfo[] logEvents)`
   5.`FlushCurrentFileWrites`: from `MemoryStream` to `byte[]` (`.ToArray()`

also `AsyncRequestQueue.DequeueBatch` uses a `ToArray`, this unneeded?

Proposal:
- remove all conversion to bytes
- remove unneeded `ToArray()`

**Comment by 304NotModified** [comment]
Breaking change because of protected methods

**Comment by imanushin** [comment]
Moreover, conversion to string is not needed too, however this can lead to a huge refactoring.
For my opinion, the best idea is:
1. Support rendering to Stream support:
1.1 Add IStreamLayout interface with method: void RenderToStream(AsyncLogEventInfo event, Stream outputStream);
1.2. Implement this interface in the NLog layouts
1.3. Implement wrapper: to have ability to work with any Layout, event without IStreamLayout implementation
2. Change events render schema: instead of string creation we should write into the intermediate MemoryStream directly.

As a result we can decrease memory traffic and decrease Gen 0 allocations count. Then we can continue with the steps above:

3. Change methods of BaseFileAppender: 
3.1 Instead of byte[] we should work with Streams (e.g. we should read length, copy data and do any other works with Stream class, this is too simple)
3.2 Possible, we should facade Stream to IReadOnlyStream with methods "Lendth, CopyTo(Stream destination)" and couple other.

If there are not objections, I can create prototype.

**Comment by snakefoot** [comment]
If we changed TransformBytes to work on the MemoryStream directly (along with a start offset), then it could become:

1) Layout-string -> Target-StringBuilder
2) Target-StringBuilder -> Target->CharBuffer (Encoding)
2) Target-CharBuffer -> Target-MemoryStream (Encoding)
3) Target-MemoryStream -> FileStream

Then you will get rid of one memcpy. Not sure if you can optimize any more.

**Comment by snakefoot** [comment]
This change improved the perfomance from 1.834.774 msgs/sec to 2.145.173 msgs/sec. for #1799

**Comment by snakefoot** [comment]
Guess this can be resolved with #1871 and #1799

**Comment by 304NotModified** [comment]
indeed \0/
