### ISSUE TITLE
Improve Install of targets / crash Install on Databasetarget. 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1098]
Calling `Install` on a databasetarget leads to a nullrefexception (https://github.com/NLog/NLog/issues/1094). The work around is to call `Initialize` on the `LoggingConfiguration`, as seen on  [InstallNLogConfig console application](https://github.com/NLog/NLog/blob/master/src/InstallNLogConfig/Program.cs)

A public method should never throw this kind of exception. We have to find out why `Install` isn't calling `Initialize`.

Steps:
- [ ] check if other targets won't call `Initialize` in `Install`
- [ ] discuss the impact of call `Initialize` in `Install`
- [ ] OR fix the nullref, OR call `Initialize` in `Install`

**Comment by mustafadinler** [comment]
Is there anybody working on this issue? I want to do it.

**Comment by 304NotModified** [comment]
Nope, please do :)

**Comment by UgurAldanmaz** [comment]
@mustafadinler, do you need any help on this?

**Comment by 304NotModified** [comment]
Someone working on this?

**Comment by M4ttsson** [comment]
Is anyone working on this? If not, may I have a look? I guess a good start would be to reproduce the error in the bug report and find the null reference. Then try the same for other installable targets. Am I on the right track?

**Comment by UgurAldanmaz** [comment]
Thanks @M4ttsson. Do not hesitate to have a look. No one workig on this. 

Reason of null reference exception is discussed at #1094. You can find more info at there.

**Comment by M4ttsson** [comment]
Thanks. I managed to reproduce it yesterday. But unfortunately I don't have any more time this week so I'll continue next week.

**Comment by 304NotModified** [comment]
👍

**Comment by M4ttsson** [comment]
I opted to fix the nullref by refactoring a small part of the InitializeTarget method and use it in Install. Calling InitializeTarget method in Install would if I'm not mistaken scan for layouts among other things so a null check inside Install should be the solution with the least impact.
The other IInstallable's Installs works similarly, neither makes any calls to InitializeTarget or Initialize. But they make calls to some methods that is also used in InitializeTarget. 

I'm new to using NLog but this is my thoughts on calling Initialize from Install. Doing so would also require the Target to be complete. I.e. all required parameters need to be set. This would probably not be an issue when using xml config, but when configuring with code it might be harder to understand. Since one might prepare the target for installation and install before continuing with the rest and configure the target for logging. At least when creating a new DatabaseTarget to verify that the table is created before spending too much time on configuration. 

I'll create a pull request in a moment.
