### ISSUE TITLE
Document ThreadAgnostic attribute / PrecalculateVolatileLayouts 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1136]
Document in code better:
- [`ThreadAgnostic` attribute ](https://github.com/NLog/NLog/blob/c07418d87b991b1cb9b42d61ae9c5dbc1e41b65a/src/NLog/Config)/ThreadAgnosticAttribute.cs
- [`PrecalculateVolatileLayouts`](https://github.com/NLog/NLog/blob/c07418d87b991b1cb9b42d61ae9c5dbc1e41b65a/src/NLog/Targets/Target.cs#L149)
- IsThreadAgnostic for Target

See https://github.com/NLog/NLog/issues/1105

**Comment by TheXenocide** [comment]
I'm having an issue which I believe resembles #1105 which I was going to start a new bug for, but wanted to verify that my expectations/understanding were accurate. Is it correct that, as long as any layout or renderer in the object graph for a given target is NOT marked with `ThreadAgnosticAttribute`, the render should happen on the original thread, even if the target is an async/buffered file target? I have made some layouts/renderers which I'm using to log custom contextual properties from CallContext (similar to how the MappedDiagnosticLogicalContext works, but a bit different). The problem I'm having is that none of the properties exist during the `Layout.GetFormattedMessage` or `LayoutRenderer.Append` overrides. I have not marked them `ThreadAgnostic` because I know they aren't, but it seems like my objects are being invoked on the wrong thread since I have access to the data where I call the logger.

**Comment by 304NotModified** [comment]
The docs are a bit improved. It currently this afaik:


- if `ThreadAgnosticAttribute` isn't set,  then the layout will be rendered in the main thread ("precalculated")
- Advise:  Apply `ThreadAgnosticAttribute` on a `Layout` when:
  - The result can we rendered in another thread. Delaying this could be more efficient. And/Or,
  - The result should not be precalculated, for example the target sends some extra context information.

**Comment by 304NotModified** [comment]
> NOT marked with ThreadAgnosticAttribute, the render should happen on the original thread, even if the target is an async/buffered file target?

Yes indeed

> but it seems like my objects are being invoked on the wrong thread since I have access to the data where I call the logger.

It will be only precalculated when there is one non-threadagnostic layout: https://github.com/NLog/NLog/blob/3cbb23278b8ddb68e67f1defd796fa7d5812b331/src/NLog/Targets/Target.cs#L195

Is this `async` method? We have troubles with that as this could  be logged on the another thread.

**Comment by TheXenocide** [comment]
No async methods involved, plenty of layouts/renderers not marked thread agnostic. I have a repro in LINQPad but it references one of our proprietary assemblies; let me see if I can extract it

**Comment by 304NotModified** [comment]
Done by https://github.com/NLog/NLog/pull/1956
