### ISSUE TITLE
Configuration schema validation using XSD and XML

### ISSUE THREAD

**Issue by UgurAldanmaz** [NLog/NLog#1174]
Configuration should be validated before initialization process.

See #1121 and #1128

**Comment by 304NotModified** [comment]
Validation instead of Exception is a good idea, but not sure if we should do it by XSD.

The XSD isn't always up-to-date and it's difficult (I think) to unit test the whole config.

**Comment by Page-Not-Found** [comment]
Then I would suggest we make this a standard to make sure we update the XSD when ever needed?

**Comment by snakefoot** [comment]
NLog 4.6 + NLog 5.0 have made the NLog-Configuration-Parser more strict (alerts on unexpected/misspelled properties). Think any improvements to configuration-file validation should be implemented in the NLog-Configuration-Parser. Since XSD validation is slow, and also requires XSD matches NLog-version.

Notice also XSD validation have been implemented with #3487
