### ISSUE TITLE
Fix ${basedir} & assembly for .NET Core

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1221]
use IHostingEnvironment.WebRootPath?

See http://stackoverflow.com/questions/32631066/how-to-consistently-get-application-base-path-for-asp-net-5-dnx-project-on-both

needed for https://github.com/NLog/NLog.Framework.Logging. Maybe it should be injected from there.

**Comment by phenixdotnet** [comment]
It isn't already working ? 

The BaseDirLayoutRenderer should be working : https://github.com/NLog/NLog/blob/coreCLR/src/NLog/LayoutRenderers/BaseDirLayoutRenderer.cs

**Comment by 304NotModified** [comment]
@phenixdotnet 

Thanks for the info. This is probably fixed in NLog 4.4 alpha. is this also fixed for  .NETFramework 4.5.1? 

I tried ASPNET5 + .NETFramework 4.5.1, and I used NLog 4.0.1 - so didn't tested NLog 4.4

**Comment by 304NotModified** [comment]
edit: seems the code isn't enabled for net451, but I could be easily because the package supports it
https://www.nuget.org/packages/Microsoft.Extensions.PlatformAbstractions/

**Comment by phenixdotnet** [comment]
@304NotModified If you run on dnx (dnxcore50, dnx451) you should have the dependency, otherwise it's working like the current version on master. If I'm right the DNX const is only set on dnx target.

**Comment by 304NotModified** [comment]
Yes indeed the dnx symbol is only in the dnx version.

**Comment by 304NotModified** [comment]
info:

https://github.com/aspnet/Announcements/issues/237

**Comment by snakefoot** [comment]
> aspnet/Announcements#237

Well it seems that this is not completely true for AspNetCore applications:

Microsoft.Extensions.PlatformAbstractions | Equivalent .NET API
-- | --
ApplicationEnvironment.ApplicationBasePath | System.AppContext.BaseDirectory or System.AppDomain.CurrentDomain.BaseDirectory

Since `ApplicationEnvironment.ApplicationBasePath` used to be:

Source\Repos\NLog.Web\examples\ASP.NET Core 2\Visual Studio 2017\ASP.NET Core 2 - VS2017

But `System.AppDomain.CurrentDomain.BaseDirectory` is now:

Source\Repos\NLog.Web\examples\ASP.NET Core 2\Visual Studio 2017\ASP.NET Core 2 - VS2017 **\bin\Release\netcoreapp2.0**

But I think `${basedir}` works as intended as it correctly maps to AppDomain.BaseDirectory. One just need to think up a different layoutrenderer for AspNetCore. See also https://github.com/NLog/NLog.Web/pull/253 (`${aspnet-appbasepath}`)

**Comment by snakefoot** [comment]
@304NotModified Think this should be resolved. The AspNetCore-issue is for the NLog.Web-project.

**Comment by snakefoot** [comment]
It actually seems like with latest version of NetCore21 and VisualStudio 2017 v15.8, that the AppDomain.BaseDirectory is now the same as on full NetFramework. This hotfix will mostly help people running on older version of NetCore and VisualStudio.

**Comment by 304NotModified** [comment]
Thanks for the update, this one can be closed then.
