### ISSUE TITLE
Layout everything 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1234]
I have seen multiple requests for layout renders which have non-layoutable properties (eg string,  int) . 

I would be nice if every property would be layoutable.  

This is breaking change and needs some performance tests / tweaks. We don't expect a big performance change, see https://github.com/NLog/NLog/issues/1228

ps: There is a [`SimpleLayout .Escape(string)` method](https://github.com/NLog/NLog/blob/1899e6a4a5ab4ee0b23129d5b950cad519db19b4/src/NLog/Layouts/SimpleLayout.cs#L171). Maybe we can use that for backwards-compatibly. (e.g. when setting reading the XML)

**Comment by 304NotModified** [comment]
Proposal: create a generic Layout and default layouts for all primitive types (only if used)

e.g.

- IntLayout
- LongLayout
- ShortLayout
- BoolLayout

also probably needed 

- DateTimeLayout (LimitingTargetWrapper)
- EnumLayout<TEnum>


etc.

Would be nice if we could easier escape the values, e.g. single quotes don't get expanded (`'${myvar}'` vs `"${myvar}"` in the XML config

**Comment by 304NotModified** [comment]
@snakefoot any opinion on https://github.com/NLog/NLog/pull/3119? I like to continue on this one.

PS: there is also a really another approach possible, revert all the properties to just `string`, `int` etc and add a proxy object between the layout renderers - before `write`, it will update all properties. But not sure if we could get that nice in terms of performance.

**Comment by 304NotModified** [comment]
@snakefoot It this a no opinion? 👼

**Comment by snakefoot** [comment]
> @304NotModified It this a no opinion?

The issue is that I cannot see any perfect solutions. Already now the NLog-Layout logic is causing a lot confusion for new developers. Have now dived through many NLog-targets and pretty much all them was doing it wrong. Some have been fixed, but all new NLog-targets will probably also do it wrong.

My biggest worry was the performance and memory-allocation-overhead. But after having implemented `IStringValueRenderer` then the overhead has been reduced for static strings. And with some extra effort then it can also be applied to `When` and `WhenEmpty`. Just need to make sure one doesn't call `LogEventInfo.CreateNullEvent()` constantly.

I'm fine with trying to convert all string-properties to Layout. But more care has to be applied to int/enum-properties.

Also the `Layout`-type makes it less obvious what values can be assigned. This will affect the chance of creating an intuitive fluent-config-api as one have to pay attention to make property-assignment natural.

**Comment by 304NotModified** [comment]
> But more care has to be applied to int/enum-properties.

Isn't this  #3119?



> Also the `Layout`-type makes it less obvious what values can be assigned.

Would it be better if we change the name to LayoutableString or TemplatableString? (and LayoutableInt / TemplatableInt etc)

**Comment by snakefoot** [comment]
> Would it be better if we change the name to LayoutableString or TemplatableString? (and LayoutableInt / TemplatableInt etc)

I'm guessing it is the user-experience in VisualStudio that counts, whether the intellisense is working good.

**Comment by snakefoot** [comment]
`Layout<T>` has now been introduced to the audience, and some targets has also been updated to make use of it.

Some properties are harder than others to convert to new `Layout<T>` ex. `FileTarget.Encoding`.  So one should probably hand-pick those that requires minimum effort and minimum surprises.  New pull-requests can be created when finding low-hanging fruits.

**Comment by snakefoot** [comment]
One funny thought about layout everything is that one could have `${gdc:item=${event-property:item=boo}}` and if the user was able to inject user-input, so LogEventInfo contained the property `boo` then it could suddenly control the output of the Layout. Ex. dump output to filename of own choosing.

Right now because most properties are simple- and immutable-types (read not Layout), then this attack vector is pretty much non-existing.
