### ISSUE TITLE
Handle <include /> with nonexistent paths

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1360]
Using variables to include config files is a really cool feature.
`<include file="${machinename}.config"/>`

But it fails when variables expand to file names that don't exist/the user can't access

Don't throw an error when the include file is missing.

See https://nlog.userecho.com/topics/18-handle-include-with-nonexistent-paths/

**Comment by 304NotModified** [comment]
This is already implemented:

` <include file='included-notpresent.nlog' ignoreErrors='true' />`

**Comment by senj** [comment]
The problem with this solution is that I will have multiple file locations if it actually finds the file.
Because this

```
<include file="default.config" />
<include file="${machinename}.config" />
```

will log in default.config AND {machinename}.config. But what I want is that IF it finds machinename.config, DON'T log in default.config.

Or can you explain where the targets and rules sections have to be placed to make this work please

**Comment by 304NotModified** [comment]
Agree, that case isn't working yet. Could you do a proposal how to configure that? (in a new Github issue please)
