### ISSUE TITLE
${level:uppercase} won't work

### ISSUE THREAD

**Issue by kwaak** [NLog/NLog#1372]
**Type** (choose one):

- Bug

**NLog version**: (4.2.1)

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
${level:uppercase}
```

In case of a BUG:

- What is the current result? no UPPERCASE
- What is the expected result? UPPERCASE
- Are there any work arrounds? yes: `${level:uppercase=true}`

**Comment by mathieubrun** [comment]
[LayoutParser.ParseLayoutRenderer](https://github.com/NLog/NLog/blob/master/src/NLog/Layouts/LayoutParser.cs#L353) will consider this as a property of the wrapped layout renderer, and does not create the wrapper.

Adding some logic to try to create the wrapper after [InternalLogger.Warn("{0} has no default property", lr.GetType().FullName);](https://github.com/NLog/NLog/blob/master/src/NLog/Layouts/LayoutParser.cs#L433)  could be the way to go ?

**Comment by mathieubrun** [comment]
Added implementation proposal : https://github.com/NLog/NLog/pull/1419

**Comment by 304NotModified** [comment]
This isn't a bug, but intended behavior in the parser.

`${level:uppercase}` isn't correct, as the parser will read `uppercase` as a default parameter of `Level`.

We will not change this in the parser, because then changing ambient properties / default parameters of targets could (indirectly) influence each other.

**Comment by 304NotModified** [comment]
Thanks @mathieubrun for helping us on this!
