### ISSUE TITLE
Remove AspNetCore.Hosting dependency

### ISSUE THREAD

**Issue by smbecker** [NLog/NLog#1475]
**Type**: Feature Request
**NLog version**: 4.4.0-beta8
**Platform**: CoreCLR

Unless I am missing something, which is very possible, it seemed to only be used when trying to get the base directory, which should be accessible using AppContext per my review comment [here](https://github.com/NLog/NLog/commit/52bd669fc5e11615f6ae07d234ccdf0cb5b9d47e#commitcomment-17564952). Can AspNetCore.Hosting and PlatformAbstractions be removed?

**Comment by 304NotModified** [comment]
Sounds like a good plan! Can you send a PR for that? 

This is also needed for autoloading, see https://github.com/NLog/NLog/blob/7035e5bda5126ef46faa517e9a6ae8301ef0835b/src/NLog/Config/ConfigurationItemFactory.cs#L239 (note: "netstandard1.3" has the UWP10 conditional symbol, that will be fixed in the future)

**Comment by 304NotModified** [comment]
@phenixdotnet I guess we can tollally get rid of constructor: `public BaseDirLayoutRenderer(IHostingEnvironment appEnv)` ?

**Comment by 304NotModified** [comment]
Pretty sure it isn't used, also same unit tests fails (minor issues)

So removed and released: https://www.nuget.org/packages/NLog/4.4.0-beta9 :)
