### ISSUE TITLE
Changing connectionStringName dynamically

### ISSUE THREAD

**Issue by danaERadwin** [NLog/NLog#1541]
Hi! 
**Type**: Bug

**NLog version**: (e.g. 4.3.5)

**Platform**: .Net 4.6

**Current NLog config** (xml)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Debug" internalLogFile="C:\logs\App\nlog.txt" >

  <variable name="myvar" value="myvalue"/>
  
<targets>
    <target name="file"
        xsi:type="File"
        fileName="C:\logs\App\log.log"
        layout="
-------------- ${level} (${longdate}) --------------${newline}
${newline}
Call Site: ${callsite}${newline}
Line Number: ${callsite-linenumber}${newline}
Exception Type: ${exception:format=Type}${newline}
Exception Message: ${exception:format=Message}${newline}
Stack Trace: ${exception:format=StackTrace}${newline}
Full Exception: ${exception}${newline}
Additional Info: ${message}${newline}" />
    
    <target name="database"
      xsi:type="EntityFramework"
            connectionStringName ="ConnectionStringA"
            commandText="exec InsertLog
                @userName,
	              @logType,
	              @details,
	              @exceptionType,
	              @exceptionMessage,
	              @exceptionStackTrace,
	              @exceptionInnerInfo
            ">
      <parameter name="@userName" layout="UserName"/>
      <parameter name="@logType" layout="${level}"/>
      <parameter name="@details" layout="${message}"/>
      <parameter name="@exceptionType" layout="${exception:format=Type}"/>
      <parameter name="@exceptionMessage" layout="${exception:format=Message}"/>
      <parameter name="@exceptionStackTrace" layout="${exception:format=StackTrace}"/>
      <parameter name="@exceptionInnerInfo" layout="${exception:method:maxInnerExceptionLevel=5:innerFormat=shortType,message,method}"/>
    </target>
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="file" />
    <logger name="database" minlevel="Trace" writeTo="database" levels="Warn,Error" />
  </rules>
</nlog>
```
**Configuration of the connectionStringName using the API:**
```
public void ChangingConnectioniStringName(string connectionStringName, Exception e)
        {
            var config = LogManager.Configuration;
            var dbTarget = (EntityFrameworkTarget)config.FindTargetByName("database");
            dbTarget.ConnectionStringName = connectionStringName;
            LogManager.ReconfigExistingLoggers();
            logger.Error(e, message);
        }
```

My code uses Nlog and Entity Framework.
I  am trying to edit the connection string name dynamically, the DBs share the same table's schema.
The connectionStingName should change after using my "ChangingConnectioniStringName" function, that uses the API. I could see that the connectionStringName in the target is changed to the new connectionStringName, but the logger.Error line is saving the message and the exception details in the hard coded (old) connectionStringName database.
I was expecting to see that the data will be written in the new connectionStingName database.

Thanks

**Comment by 304NotModified** [comment]
I think the connection is kept open. We need a force close I guess

**Comment by 304NotModified** [comment]
I checked the code and this should work

See 

```
        private void EnsureConnectionOpen(string connectionString)
        {
            if (this.activeConnection != null)
            {
                if (this.activeConnectionString != connectionString)
                {
                    InternalLogger.Trace("DatabaseTarget: close connection because of opening new.");
                    this.CloseConnection();
                }
            }

            if (this.activeConnection != null)
            {
                return;
            }

            InternalLogger.Trace("DatabaseTarget: open connection.");
            this.activeConnection = this.OpenConnection(connectionString);
            this.activeConnectionString = connectionString;
        }

```

Please check the internal log

**Comment by danaERadwin** [comment]
Thank you so much for the quick response!
What does the this referred to?

**Comment by 304NotModified** [comment]
See link in text of https://github.com/NLog/NLog/issues/new

**Comment by 304NotModified** [comment]
Is this still an issue?

I'm pretty sure it should work but too bad I haven't found time to debug stuff

**Comment by danaERadwin** [comment]
Hi,
Yes, this is still an issue.
The code in the EnsureConnectionOpen is not working since I cannot access all of these methods,
and my code is not changing the connection properly.

**Comment by 304NotModified** [comment]
this is strange as before every write, we rebuild the connectionstring:
https://github.com/NLog/NLog/blob/8ec0bf3593c208bbe2eddf669b7f48046461cc63/src/NLog/Targets/DatabaseTarget.cs#L492

and it's using the ConnectionString property: https://github.com/NLog/NLog/blob/8ec0bf3593c208bbe2eddf669b7f48046461cc63/src/NLog/Targets/DatabaseTarget.cs#L540-L545

So, only changing ConnectionString would be enough

**Comment by 304NotModified** [comment]
Please fill in these texts:

----

Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.


**Type** (choose one):

- Bug
- Feature request
- Question


**NLog version**: (e.g. 4.2.3)

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin iOs

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets>
  </targets>
  <rules>
  </rules>
</nlog>

```

In case of a BUG:

- What is the current result?
- What is the expected result?
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
- Please post full exception details (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes/no
- Is there a version in which it did worked? 
- Can you help us by writing an unit test?


in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - An example of the XML config, if relevant. 


----

**Comment by UgurAldanmaz** [comment]
We should not to discuss the problem on `DatabaseTarget`. Because @danaERadwin is using `EntityFrameworkTarget`.

If I found true source code, there are some differences between our `DatabaseTarget` . @danaERadwin  check and verify the [repository](https://github.com/ladenedge/NLog.EntityFramework).

It does not work as our `DatabaseTarget`: 
* It [does not build connection string before writing a log](https://github.com/ladenedge/NLog.EntityFramework/blob/ae3491306f4a851b704b52d4e872bbb8d9610dac/EntityFrameworkTarget.cs#L154).

* It uses the same [connection](https://github.com/ladenedge/NLog.EntityFramework/blob/ae3491306f4a851b704b52d4e872bbb8d9610dac/EntityFrameworkTarget.cs#L87) once it instantiate one.

* It also set `KeepConnection` to true by default. So that [connection does not close ](https://github.com/ladenedge/NLog.EntityFramework/blob/ae3491306f4a851b704b52d4e872bbb8d9610dac/EntityFrameworkTarget.cs#L145) after writing log. Therefore, probably, it continue to use the same connection even if you reconfig.



What can you do:
* Configure `KeepConnection` to false explicitly and test again.
* If there is not any specific reason to use `EntityFrameworkTarget`, retry with `DatabaseTarget`.

**Comment by 304NotModified** [comment]
Indeed, this question is wrong here. We don't supply the entity framework target and so we can't support it.
