### ISSUE TITLE
Add context on logger level

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#1615]
Feature:

We like to do:

``` c#
var logger = LogManager.GetCurrentClassLogger();
logger.AddContext("declarationId", 10);
```

rendering, something like this:

LDC? "logger diagnostic context"

```
${ldc}
```

**Comment by poma** [comment]
Logger already provides us with a class name when we render a message. But what if I want to identify which *instance* of the class a message comes from?

I think it would be very useful if this feature allowed us to attach a context data that was visible only for messages logged from a certain instance of the class.

I'm not sure how it can be implemented though since a Logger is usually a static member and we never pass `this` reference to any logging methods. Or maybe this is a separate feature request altogether?

**Comment by poma** [comment]
By the way does `LogManager.GetCurrentClassLogger()` return the same instance when called multiple times? Because if it isn't then we can just declare Logger as an instance field and attach a class instance identifier to each logger.

**Comment by 304NotModified** [comment]
> I'm not sure how it can be implemented though since a Logger is usually a static member

`Logger` isn't `static`? `LogMananger` is

> By the way does LogManager.GetCurrentClassLogger() return the same instance when called multiple times?

it's cached by name. 

> I think it would be very useful if this feature allowed us to attach a context data that was visible only for messages logged from a certain instance of the class. So we could attach some data that identifies a class instance in a readable way.

You mean that the context data should be cleared when the Logger instance is out of scope? Manually resetting isn't a good solution?

**Comment by poma** [comment]
I was hoping to achieve something like this:

```
2016-09-07 18:34:01.1508|INFO|App.BusinessLogic.Transaction(transactionId=42)|Started processing client payment
2016-09-07 18:34:01.1508|INFO|App.BusinessLogic.Transaction(transactionId=1337)|Started processing client payment
2016-09-07 18:34:01.1508|INFO|App.BusinessLogic.Transaction(transactionId=42)|Sending request to a payment gateway
```

So that there is a way to distinguish between messages emitted by a different class instances and probably to route them to different log files if I want to. After some googling I figured out that I can just construct a differently named Logger for each class instance (I'm new to NLog). But when transactionId is embedded in Logger name string it feels that I'm doing it wrong.

**Comment by 304NotModified** [comment]
Another work around is to use the MLDC and prefix with the logger /class name?
