### ISSUE TITLE
Passing list to stored procedure

### ISSUE THREAD

**Issue by dubeme** [NLog/NLog#1627]
**Type** (choose one): Question
**NLog version**: (e.g. 4.2.3)
**Platform**: .Net 4.5
**Current NLog config** (C#, if relevant)

Hello,

I've got a Database target that will call a stored procedure, then pass in a couple of parameters. One of the parameters is of the table type. My goal is to eventually pass in a list via C#, then deal with it in the stored procedure. I've not been able to see any solution to that scenario.

I've looked into the DataBaseParameter to see if I could set the type, no success.
The only solution I can see is, passing a comma delimited string. This of course is a pain because there is no clean way to parse delimited string in TSQL.

Is there a way to actually do this.

Thank you.

**Comment by 304NotModified** [comment]
Currently only `string` parameters are supported in NLog.

Passing list to a (SQL Server) database procedure is not easy as SQL Server doesn't support lists/arrays.

There are the following solutions to fix this:

1. Use a Table Value Type, which I would only use in bulk inserts as the usages and administration could be difficult.
2. Send a comma or semicolon separated string an parse it with a SPROC: Like this http://stackoverflow.com/a/37771583/201303
3. Send XML and parse the XML in the SPROC. 

I would recommend 2 if you have control of the data (e.g. no user input) and otherwise 3.

**Comment by dubeme** [comment]
Thanks @304NotModified 

I went with option 2, but used this instead [http://stackoverflow.com/a/10914602](http://stackoverflow.com/a/10914602). 

The first option is what I was going for, but couldn't quite get how to make it work. I already have a SPROC, and a user defined table type. The issue now lies with passing in the data in the right format.

**Comment by 304NotModified** [comment]
> The first option is what I was going for, but couldn't quite get how to make it work. I already have a SPROC, and a user defined table type. The issue now lies with passing in the data in the right format.

Working with TVT in C# is always a bit pain IMO. We (at my work) do it sometimes, if there is big benefit. But most of the time we go for option 2/3.

I don't think we really need support in NLog for TVT, because that's only suitable for bulk inserts IMO.

**Comment by dubeme** [comment]
If you don't mind me asking, you keep talking about bulk inserts. Do you mean buffering up the logs, then writing to a target. n this case a DB.

**Comment by 304NotModified** [comment]
yes buffering first,

but it's more that I would use bulk inserts with logging (but in other data processes).

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
