### ISSUE TITLE
AssemblyVersion not updated with each new NuGet-Version of NLog

### ISSUE THREAD

**Issue by ArchonMegalon** [NLog/NLog#1765]
Hi! 

**Type**: Bug (kind of)

**NLog version**: any (since 4.0 )

**Platform**: any (not checked, found in 4.5)

In case of a BUG:

- What is the current result?
Currently all NLog.dlls (from every version) have the same Dll-AssemblyVersion Attribute (4.0.0.0)

- What is the expected result?
Every version should have a new (higher) AssemblyVersion-Number then the previous one.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
not relevant

- Please post full exception details (message, stacktrace, inner exceptions)
"Method not found: '!!0 NLog.Config.LoggingConfiguration.FindTargetByName(System.String)'."

- Are there any workarounds? yes and no
Normally this isn't a problem, since the NLog.dll is in the same directory as the it referencing assembly. That's probably the reason, this hasn't come up before. But that's not working for us anymore. We do use NLog in different projects in different environments (Dev, Test, Migration, pre- and production) and some (rather big) programs - for example MS Biztalk - require dll to be installed in GAC. There, the dll is identified with its AssemblyVersion.

Now in "another project" we depend on NLog of an higher version (that is - Nuget-Version-Number-"Version" > 4.3.9) then the one installed long ago in the GAC (I don't know the versionnumber, but its obviously one, where the function "FindTargetByName" was not jet implemented). Of course the "new" NLog.dll is in the program-directory. But since "another project" references "NLog 4.0.0.0" (AssemblyVersion) AND the .net-Framework finds this version in the GAC (which is actually the old version with the same number), it "loads" the one from the GAC because of priorization-rules in the framework and NOT the one in the same directory. Then tries to invoke the methods it should and - there comes the TargetInvocationException.

- Is there a version in which it did worked? 
No

- Can you help us by writing an unit test?
No

in case of a FEATURE REQUEST:
 
 - Why do we need it?
Well - this is also kind of a feature request. We need it, because it's the correct thing to do. Newer versions should have higher version-numbers. Also, the guys from the other project flatout refused to update the GAC because "it works" (for them).

Best would be, if there would be a script (or something), which updates the AssemblyInfo.cs-Files in each of the NLog-Projects with each build. I do have written such a pre-build-task and could supply some code-samples if needed.

**Comment by 304NotModified** [comment]
This is on purpose. All versions are semver compliant. Only the file version will be updated. 

Now on mobile, will respond in more detail later.

**Comment by 304NotModified** [comment]
Related http://nlog-project.org/2015/09/12/nlog-4-1-1-has-been-released.html

**Comment by 304NotModified** [comment]
See also http://stackoverflow.com/questions/64602/what-are-differences-between-assemblyversion-assemblyfileversion-and-assemblyin?rq=1

**Comment by 304NotModified** [comment]
See also http://stackoverflow.com/a/802038/201303

**Comment by 304NotModified** [comment]
There are multiple options regarding strong names and assembly versions:

## Change assembly version, no strong naming
This works nicely for people who don't need strong naming. But when strong naming is required (e.g. GAC), then those guys are struck

## Change assembly version & strong naming
When enabling strong naming, people needed it will be happy. Too bad this will give (unneeded runtime) issues when you mix two NLog versions (e.g. 4.3.8 and 4.3.9) and not using the GAC. You need those `<bindingRedirect>` in your .config, which is a lot of trouble. Also patching NLog without rebuilding is impossible. 

This will give so much trouble and constant support questions, that this is the reason some will drop those strong named dependencies, [like RestSharp](https://groups.google.com/forum/#!msg/restsharp/yjGCtOnEYHk/XbKZi0yjN8cJ).

Also we have those annoying strong name libraries at our company, and syncing those  `<bindingRedirect>` is always an issue - so we stopped with upgrading those libraries...

## Fixed assembly version & strong naming
The `<bindingRedirect>` is fixed (no need) and as long you're using always the same or newer NLog version, it all works because we're using semver. 
Too bad you're right this could give an issue when combining the GAC with the non-GAC (bin folder), as the GAC will always get loaded before the bin :(


----

IMO you should chose between GAC or non-GAC and not mix them. 
Another option is to keep using the same (max) version as in the GAC. 

> Also, the guys from the other project flatout refused to update the GAC because "it works" (for them).

That sounds IMO a bigger problem.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
