### ISSUE TITLE
Wrong date filename when archiving every day and log at midnight

### ISSUE THREAD

**Issue by SvenTobback** [NLog/NLog#2224]
**Type**:

Bug

**NLog version**: 

4.4.11

**Platform**: 

.Net 4.5

**NLog config**

```xml
<nlog>
    <targets async="true">      
      <target name="fileLocal" type="File" fileName="C:\ApiServer\DVLP_apiServer.${shortdate}.log"
              layout="${longdate} - ${level} ${logger} [${threadid}]: ${message} ${exception:format=Message,StackTrace}"
              archiveFileName="C:\ApiServer\DVLP_apiServer.${shortdate}_archive#{#}.log"
              archiveAboveSize="104857600" archiveEvery="Day" archiveNumbering="Rolling" maxArchiveFiles="100"/>
    </targets>
  </nlog>
```

**Bug**: 

When setting NLog to archive daily and a log message is added at midnight (23h59), the date in the filename of the archive does not match the date of the content of that archive. If the last log message is not at midnight, there is no problem.

![image](https://user-images.githubusercontent.com/12933037/28527028-9b22843a-7089-11e7-90b1-78a0603b93f8.png)

First log to file 23-07-2017 00:01
Last log to file 23-07-2017 23:59

Expected: Archive filename: 2017-07-23.log
Actual: Archive filename: 2017-07-24_archive#0.log

**Comment by snakefoot** [comment]
The problem is the us of `${shortdate}` here:

`archiveFileName="C:\ApiServer\DVLP_apiServer.${shortdate}_archive#{#}.log"`

It will use the date of the LogEvent currently being written, instead of the date of the previous LogEvent.

Alternative solution is this:

`archiveFileName="C:\ApiServer\DVLP_apiServer\archive\{#}.log" archiveDateFormat="yyyy-MM-dd" archiveNumbering="DateAndSequence" `

**Comment by SvenTobback** [comment]
@snakefoot Thx for the help!

If you are saying that {shortdate} will always use the date of the LogEvent that creates the archive, I don't see why this isn't an issue when it is not midnight? 

Close because the alternative solution works
