### ISSUE TITLE
.Net Standard 2.0 + NLog.Web.AspNetCore 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2294]
@i02coroj commented

> Hi all.
Sorry if this is a stupid question.
I'm working right now in a .Net Standard 2.0 project. So I would need use this last NLog version supporting it.
But looking in Nuget gallery I see the package NLog.Web.AspNetCore is not updated since more than 3 months ago, so it obviously doesn't contain all this new stuff.

> Do you have in mind upload it? How could I use it in the meantime? Am I forced to include the libraries inside my project? Thank yoj.

**Comment by 304NotModified** [comment]
We have to update NLog.Web.AspNetCore  + NLog.Extensions.Logging for .NET standard 2 (NLog 4.5 beta)

> Do you have in mind upload it?

It's probable a bit more work. Don't expect it this week. 



> Am I forced to include the libraries inside my project? Thank yoj.

Or use the latest NLog 5 beta (which gives warnings, but works on .NET standard), or include the sources ofNLog.Web.AspNetCore  + NLog.Extensions.Logging in your project

**Comment by 304NotModified** [comment]
NLog.Extensions.Logging has been updated,

next is NLog.Web.AspNetCore.

Unfortunately it's not fully clear to me which changes are (all) needed. If you could help me with that, that would be great!

**Comment by i02coroj** [comment]
Hi @304NotModified. Thanks for answering.
When you say "which gives warnings, but works on .NET standard" you mean .Net Standard 2.0?
Because I've given it a try and yes, it works, but not fully.
- LogTrace doesn't work (even when the trace level is correclty set up for the target). it's strange because LogInformation, LogWarning ... do work.
- Some variables (for example ${aspnet-request-url}) don't work.

I've taken a look to the internal log file and there is nothing remarkable.
Thanks again!

**Comment by 304NotModified** [comment]
> When you say "which gives warnings, but works on .NET standard" you mean .Net Standard 2.0?

Works for both 

> In particular I see that LogTrace doesn't work (even when the trace min level is correctly set up to Trace for the target). it's strange because LogInformation, LogWarning ... do work.

That a feature of .NET Standard 2. Use `ILoggingBuilder.SetMinimumLevel()` . Added also notes in the readmes, as its a common question: https://github.com/NLog/NLog.web#aspnet-core

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
