### ISSUE TITLE
File target ignores Compressed option specified in fileAttributes [known issue]

### ISSUE THREAD

**Issue by johnnyjob** [NLog/NLog#244]
It seems that Compressed option is ignored by File target. Use this sample project to reproduce the bug: https://skydrive.live.com/redir?resid=DF959DE37F64E71D!157&authkey=!AHQsJ6pHwtx1Mbk

Reproduced in NLog 2.0.0.2 for .Net 3.5 (binaries can also be found in the sample project).

I also reviewed NLog code tagged 2.0.0.2000. It seems that Compressed attribute is passed as a parameter to CreateFile Win32 function. But MSDN states: 
"You cannot use CreateFile to control compression, decompression, or decryption on a file or directory."
from here: http://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx

According to MSDN: "To modify the FILE_ATTRIBUTE_COMPRESSED attribute for a file or directory, you must use the DeviceIoControl function with the FSCTL_SET_COMPRESSION control code."
from here: http://msdn.microsoft.com/en-us/library/windows/desktop/aa363848(v=vs.85).aspx

Search for "DeviceIoControl" within entire solution returned zero matches. I also tried to search within master branch, but got the same result.

So it seems that declared functionality about file compression is not actually implemented in NLog.

**Comment by gab** [comment]
I'm looking to replace a proprietary logging library with nlog and this is a feature nlog is missing. Creating archive files (.zip) isn't as interesting in this case since you can't open them in any tool in a transparent way, even when using Windows' "compressed folders" zip handling.

In the meanwhile I'll set archived logs to go into a folder with the compressed flag on, but this is not ideal since to automate deployment, I'll have to add code to my executable to create said folder and set the flag on it. I'd rather have everything log-related handled by the nlog config file.

**Comment by 304NotModified** [comment]
it would boost implementing/ fixing this when we have a working example in C# to set the attribute.  Or a PR ;)

**Comment by 304NotModified** [comment]
Docs

http://stackoverflow.com/questions/624125/compress-a-folder-using-ntfs-compression-in-net

**Comment by 304NotModified** [comment]
By the way, zip compression will be added in 4.0.  See #560 which is already merged in the trunk. 

.Net45 only.

**Comment by 304NotModified** [comment]
not sure if we should fix this if this isn't supported by .Net

**Comment by 304NotModified** [comment]
Will close this as this is a known issue as it's polluting the issue list - there is no action for us here.
