### ISSUE TITLE
Span<T> opportunities

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2454]
Check the opportunities with the new `Span<T>`

see http://adamsitnik.com/Span/

@snakefoot any thoughts on this?

**Comment by snakefoot** [comment]
Not sure if iteration of string-chars will be faster when `AsSpan` from https://www.nuget.org/packages/System.Memory/.

But I guess if you need to do some logic on sub-string, then it will be faster to operate on the Span<T> instead of allocating the sub-string. But I have not found many places where SubString is used, where one doesn't want the string-allocation.

For normal arrays, then we already have ArraySegment as a non-allocating way to operate on a sub-array.

**Comment by 304NotModified** [comment]
The `TemplateEnumerator` uses `SubString` ;)

**Comment by snakefoot** [comment]
> The TemplateEnumerator uses SubString()

Do you mean the SubString() in ParseFormat() ? If so then you want the string-allocation for the format-string. 

I guess you could avoid the string-allocation of common format-strings, but again this could mean caching (similar to string-intern) and Span<T> cannot be used as cache-key.

**Comment by 304NotModified** [comment]
was thinking you could making the "new string" lazy until needed. (as in at rendering). 

But have to read more about `Span<T>` first

**Comment by snakefoot** [comment]
> was thinking you could making the "new string" lazy until needed

`Span<T>` can only be on the stack (Cannot be stored on a class-object). If you want lazy-handling, then you need something like this:

```
struct HoleName
{
     string MessageTemplate;
     int HoleNameStartIndex;
     int HoleNameLength;
}
```

But then the PropertiesDictionary is going to be even more funky (unreadable).

One could consider having an MruCache of Hole-names as the dictionary-lookup will be faster than string-allocation (And the same hole-names will be very frequent). The problem is that very few caches are super concurrent, and will instead introduce a penalty when multi-threaded.

**Comment by 304NotModified** [comment]
Thanks for the input @snakefoot 

Closing this, as there isn't something to do here
