### ISSUE TITLE
AsyncTargetWrapper loses MDLC context when puts event to parallel thread

### ISSUE THREAD

**Issue by datsis** [NLog/NLog#2465]
**Type**:
- Bug

**NLog version**: 
- 4.5.0 rc2

**Platform**: 
Checked only on .Net 4.5 

**Current NLog config** (xml or C#, if relevant)
```xml
<nlog>
  <targets>
    <default-wrapper xsi:type="AsyncWrapper" overflowAction="Block" />
    <target name="aiTarget" type="ApplicationInsightsTarget"/>
  </targets>
  <rules>
    <logger name="System.*"    maxlevel="Info" final="true" />
    <logger name="Microsoft.*" maxlevel="Info" final="true" />
    <logger name="*" minlevel="Trace" writeTo="aiTarget" />
  </rules>
</nlog>

```

In case of a BUG:

Context:
There is disposable scope which adds data into MDLC when it's created and removes these data from MDLC when disposing.  Let's name it "scoped data".
LogEvent "X" is generated by Logger.Info(...) which is called inside of scope.

- What is the current result?
Output of aiTarget does not contain "scoped data" for event "X".
- What is the expected result?
Output of aiTarget should contain "scoped data" for event "X".
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No
- Please post full exception details (message, stacktrace, inner exceptions)
There were no any exceptions
- Are there any work arrounds? yes/no
Yes, I had to create class derived from AsyncWrapperTarget which takes "scoped data" and adds it to logEvent.Properies collection before LogEvent is passed to parallel thread.
- Is there a version in which it did worked? 
Don't know.
- Can you help us by writing an unit test?
Probably.

**Comment by snakefoot** [comment]
Remember you need to access the MDLC-properties using a layout-renderer ex: `${mdlc:item=PropertyName}` -

https://github.com/NLog/NLog/wiki/MDLC-Layout-Renderer

Or by creating a custom layout renderer, and extract the value from the MappedDiagnosticsLogicalContext:

https://github.com/NLog/NLog/wiki/How-to-write-a-custom-layout-renderer

**Comment by snakefoot** [comment]
Also if you are using Microsoft ApplicationInsightsTarget:

https://github.com/Microsoft/ApplicationInsights-dotnet-logging/tree/develop/src/NLogTarget

Then you will notice they are not supporting MDLC-properties. You will have to implement your own.

Ofcourse the correct solution would be that it supported any number of properties. I guess NLog should implement an extension to TargetWithLayout called TargetWithProperties (Allow easy implementation of IncludeAllProperties, MDC, MLC, etc.)

**Comment by datsis** [comment]
Let me add some additional details.
I use code pretty close to the following:https://github.com/NLog/NLog.Extensions.Logging/blob/master/src/NLog.Extensions.Logging/Logging/NLogLogger.cs.
This scope implemetation has MDLContext under the hood.

So described bug occurs in the following case.

Assume that there code fragment:
`using(logger.BeginScope(new Dictionary(){ {"key1", "value1"}, {"key2", "value2"} }))
{
logger.Info("Entering the scope");
// pretend that here goes some useful code
logger.Info("Leaving the scope");
}`

So it's expected that two log event will contain properties "key1" and "key2" when log target "print" them some how. And if target is synchronious it work as expected.

But please look what happens if target is wrapped with wrapper which uses queue and parallel thread:
`using(logger.BeginScope(new Dictionary(){ {"key1", "value1"}, {"key2", "value2"} }))
{ // here MDLC contains "key1" and "key2" properties
logger.Info("Entering the scope"); // here event has been added to queue of parallel thread
// pretend that here goes some useful code
logger.Info("Leaving the scope"); // here event has been added to queue of parallel thread
}
// here MDLC does not contain "key1" and "key2" properties`

So if async wrapped target "prints" log event after leaving of the scope then events will be "printed" without "key1" and "key2" properties.

Does this description work for you?

**Comment by snakefoot** [comment]
> Does this description work for you?

Not sure what you are trying to explain, but yes BeginScope can inject properties into MDLC, and when disposed then they are removed again.

Seems you didn't understand my first post. Please read it again, and explain what parts you don't understand about how you use the layout-renderer  in the output-target.

**Comment by datsis** [comment]
Seems you didn't understand bug description.
I do not have any questions about mdlc-layout-renderer in output target. 
Moreover mdlc-layout-renderer is useless in the context of this bug. 
Because it's impossible to configure output target with mdlc-layout-renderer since it's totally unpredictable which properties would be added inside of scope of BeginScope.

There are not question about ApplicationInsightsTarget. It's pretty trivial and expected that target knows nothing about MDLC and just outputs logEvent.Properties. It's exptected.

Please note that this bug description is about following points:
1. If ApplicationInsightsTarget (or Seq or other)  is used then context data of a scope is printed by target to output. So all work fine.
2. If working target is wrapper with AsyncWrapperTarget that underlying target does not print context data of a scope ever. Because when an event is printing a scope already is disposed and context data has been lost. Which is not exptected behavior of async wrapper.  Async wapper was supposed only to add asynchronicity but not losing of data.

**Comment by snakefoot** [comment]
>There are not question about ApplicationInsightsTarget. It's pretty trivial and expected that target knows nothing about MDLC

That is the problem. NLog expects that the targets knows about MDLC, and knows how to capture the it also in async-mode. Special logic has to be implemented in all targets that wants to support MDLC-properties.

Believe that the NLogViewerTarget is the only target in the world that correctly support MDLC. For all other targets then the only option is to support usage of JsonLayout.

I'm not saying that this is super optimal. And I would prefer it was a lot easier to write NLog-targets that supported MDLC out of the box.

I'm still trying to wrap my brain around how the ApplicationInsightsTarget (or Seq) is able to capture MDLC-properties (coming from BeginScope), since they don't inspect MDLC-properties. So I cannot understand how you make BeginScope work when not using AsyncTargetWrapper.

**Comment by datsis** [comment]
> how the ApplicationInsightsTarget (or Seq) is able to capture MDLC-properties
They didn't. The fastest workaround was found is to do something like that:
```
 private void AppendWithMdlcProperties(LogEventInfo logEvent)
        {
            foreach (var rawKey in MappedDiagnosticsLogicalContext.GetNames())
            {
                var key = GetPropertyBagKey(rawKey);
                var value = MappedDiagnosticsLogicalContext.Get(rawKey);
                if (!logEvent.Properties.ContainsKey(key))
                {
                    logEvent.Properties.Add(key, value);
                }
                else
                {
                    logEvent.Properties[key] = $"{logEvent.Properties[key]},{value}";
                }
            }
        }
```
And put it at the appropriate place to class derived from ApplicationInsightsTarget.

But in this case another issue occurs. How to do not append twice if there are two CustomApplicationInsightsTarget appears in the configuration.

**Comment by snakefoot** [comment]
> They didn't. The fastest workaround was found is to do something like that:

Yes that explains it. You have met the pitfall of how NLog handles MDLC (or MDC, NDC, NDLC), that right now is rather cumbersome for custom targets. You need to signal to NLog that it should capture the async-data before doing the async-logging.

Normally this done by having a NLog-Layout on the Target that signals to NLog that it wants to render the async-data to a string-value before doing the async-logging.

I can see your case is a little different, since you just want to inject the async-data directly into the LogEventInfo-properties. I guess this will work fine if everyone can promise that the async-data-objects injected into BeginScope are immutable.

The problem is that modifying the NLog LogEventInfo any other place than in the logger itself will cause race-conditions. The same LogEventInfo object is forwarded to all relevant targets, and the unwritten contract is that no target should modify the LogEventInfo.

Your case could probably be handled by having the Logger-object itself to perform the capture of async-data, before broadcasting it to the destination targets.

**Comment by snakefoot** [comment]
The only workaround right now, when using NLog targets that doesn't support MDLC is to use the example `Log<TState> Simple`

https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-properties-with-Microsoft-Extension-Logging

Where you implement a helper method that injects the async-data into `TState`.

**Comment by snakefoot** [comment]
@datsis Have created an issue about improving the handling of MDLC-properties; #2466 (Maybe you have comments to the suggested solutions, or maybe have some yourself)

**Comment by snakefoot** [comment]
@datsis Made an attempt to make it easier to capture MDLC-properties when in async-mode. See #2467

The target just have to inherit from the new `TargetWithContext`, and then it will automatically have the ability to capture MDLC-properties, so they also work in async-mode.

Just have to call `GetContextMdlc` in the override of `Write(LogEventInfo)`, instead of directly accessing the MDLC-container. You can see the very simple unit test how to use it.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
