### ISSUE TITLE
Release 4.5 RTM todo

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#2498]
todo list.

See https://github.com/NLog/NLog/milestone/27

**Comment by 304NotModified** [comment]
@sandersaares @snakefoot 

to be transparant, I think this list is up-to-date. Will try to release 4.5 RTM in a few weeks.

**Comment by sandersaares** [comment]
I reiterate a need for stable versions.

I am currently looking for an NLog alternative because I cannot publish libraries that depend on NLog if NLog is a prerelease version. The functionality is all there but without the packages, it is not usable to me.

**Comment by 304NotModified** [comment]
feel free to contribute so we could move faster.

**Comment by sandersaares** [comment]
Well, all the parts of NLog that I care about (the functionality) are there. The only contribution I would really be motivated in right now is to press the publish button to make the current version live.

**Comment by wonea** [comment]
Agreed, it is stable for me. I would like a release version, would make my build process in NET STANDARD much easier.

**Comment by 304NotModified** [comment]
FYI there are some reported issues open, we're working on the changes, see https://github.com/NLog/NLog/pulls?q=is%3Aopen+is%3Apr+milestone%3A%224.5+rc5%22

**Comment by snakefoot** [comment]
We should probably have releases NLog for NetStandard before completing NLog structured logging, but both were huge tasks and got mixed together because of high priority and limited time. By releasing early on both features, then we could get feedback on both at the same time.

Though right now most feedback has been no feedback ;), which I guess means things are working and all the changes introduces has not caused any major show stoppers.

As mentioned by @304NotModified then there are a few PRs pending, which is better than a few issues pending. Also hoping that these will be the last for NLog 4.5, so we can get this forever rolling ball into the net. 

Going on winter holiday early Sunday, so could be nice to see a fully released NLog 4.5 when I get back :)

**Comment by snakefoot** [comment]
@304NotModified How far are we now from promoting the NLog 4.5.0-rc06 to NLog 4.5.0 RTM ? (Along with promoting NLog.Extensions to 1.0 RTM?)

**Comment by 304NotModified** [comment]
> And why are all NLog.Extensions-builds called RTM

That's a side effect of .NET core which was first RC2:

![image](https://user-images.githubusercontent.com/5808377/36599784-c32b59e6-18b0-11e8-8495-5dd01ef39306.png)


> @304NotModified How far are we now from promoting the NLog 4.5.0-rc06 to NLog 4.5.0 RTM ?

Guess some last docs (https://github.com/NLog/NLog/issues/2432) and a news post

**Comment by 304NotModified** [comment]
Just see the milestone for the latest status: https://github.com/NLog/NLog/milestone/27

**Comment by 304NotModified** [comment]
it's live! https://www.nuget.org/packages/NLog/4.5.0
