### ISSUE TITLE
archive file name: iteration instead valid date

### ISSUE THREAD

**Issue by CapitanPlanet** [NLog/NLog#2520]
**Type** (choose one):
- Bug

**NLog version**: 4.3.9

**Platform**:  .Net 4.5

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log" >
  <extensions>
    <add assembly="xxx" />
  </extensions>
  <variable name="VerboseLayout"
              value="${longdate} ${level:upperCase=true} ${message}  
                    (${callsite:includSourcePath=true})"            />
  <variable name="ExceptionVerboseLayout"
              value="${VerboseLayout} (${stacktrace:topFrames=10})  
                     ${exception:format=ToString}"                  />
  <targets async="true">
    <target xsi:type="File"
            name="default"
            archiveAboveSize="10000000"
            layout="${VerboseLayout}"
            fileName="${basedir}/logs/Log_${shortdate}.log"
            keepFileOpen="false"
            archiveFileName="${basedir}/logs/Log_${shortdate}.{##}.log"
            archiveNumbering="Sequence"
            archiveEvery="Day"
            maxArchiveFiles="50" />

<!--This target is for something else-->
    <target xsi:type="File"
      name="statistics"
      layout="${message}"
      fileName="${basedir}/${webConfig:Key=LogsFolder}/${shortdate}.log"
      archiveFileName="${basedir}/logs/statistics/archive/log{#}.log"/>
  </targets>
  <rules>
    <logger name="default" minlevel="Info" writeTo="default" />
    <logger name="Statistics" minlevel="Info" writeTo="statistics"/>
  </rules>
</nlog>
```

In case of a BUG:

- What is the current result?
Sometimes instead of valid date as file name I get date+1 and iteration (like in case of reach archiveAboveSize cap). My last files:
Log_2018-01-16.log
Log_2018-01-16.00.log (should be Log_2018-01-15; yesterday file name was correct)
Log_2018-01-15.00.log (should be Log_2018-01-14)
Log_2018-01-13.log
Log_2018-01-13.00.log (should be Log_2018-01-12)
Log_2018-01-11.log
Log_2018-01-10.log

**Comment by 304NotModified** [comment]
We've fixed things with archiving in NLog 4.4.x

Please try 4.4.12 first, thanks!

**Comment by snakefoot** [comment]
@CapitanPlanet You are using the NLog file archive logic wrong:

```
fileName="${basedir}/logs/Log_${shortdate}.log"
archiveFileName="${basedir}/logs/Log_${shortdate}.{##}.log"
archiveEvery="Day"
```
You should not specify the **${shortdate}** for the `archiveFileName`. It will use current time, instead of the time of the previous logevent (which you are expecting).

You should not specify `archiveEvery="Day"` as fileName already includes `${shortdate}`, so it will automatically roll to new file.

Instead you should do it like this, when using NLog 4.4 or older:

```
    fileName="${basedir}/logs/Log_${date:format=yyyy-MM-dd}.log"
    archiveFileName="${basedir}/logs/Log_{##}.log"
    archiveDateFormat="yyyy-MM-dd"
    archiveNumbering="DateAndSequence"
    archiveAboveSize="10000000"
    archiveEvery="Year"
    maxArchiveFiles="50"
```
- **archiveFileName** - Using {#} allows the archive cleanup to generate proper file wildcard.
- **archiveDateFormat** - Must match the ${date:format=} of the fileName (So remember to correct both date-formats, if change is needed)
- **archiveNumbering=DateAndSequence** - Configures the archive cleanup to support parsing of filenames as dates and sequence number
- **archiveEvery=Year** - Activates the archive cleanup, but also the archive file operation. Because the configured fileName automatically ensures the archive file operation, then we don't want any additional archive operations (Ex. avoiding generating extra empty files at midnight).
- **maxArchiveFiles** - How many archive files to keep around.

When using NLog 4.5 (or newer), then the following should work:

```
    fileName="${basedir}/logs/Log_${shortdate}.log"
    archiveAboveSize="10000000"
    maxArchiveFiles="50"
```

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
