### ISSUE TITLE
NLog in Unit Test (xUnit)

### ISSUE THREAD

**Issue by acidos** [NLog/NLog#2545]
I'm using NLog in the class that I intend to test using xUnit(with .NET Core 2.0). In class constructor I have the following:

    var config = new LoggingConfiguration();
    var fileTarget = new FileTarget
    {
        Layout = @"${longdate} - ${message}",
        FileName = @"log-proxy.txt",
        KeepFileOpen = false
    };
    config.AddTarget("file", fileTarget);
    ...

This works just fine from the program itself. However, FileTarget is throwing exception whenever I am running it through xUnit. Inner exception looks like this: 

>  FileNotFoundException: Could not load file or assembly
> 'System.Configuration.ConfigurationManager, Version=0.0.0.0,
> Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot
> find the file specified.

For the stand alone program I don't specifically added `System.Configuration.ConfigurationManager`. Why should I add it in unit test project? I have however added `System.Configuration.ConfigurationManager` to xUnit project, but now it leads to another exception, thrown by NLog.LogManager:
   

> MissingMethodException: Method not found: 'System.AppDomainSetup
> System.AppDomain.get_SetupInformation()'.

So I guess something is terribly wrong.

I've isolated the problem in small [project](https://www.dropbox.com/s/all1x5b86r010u3/UTCrash.zip?dl=0).

The testing method is as simple as just initializing object.

    [Fact]
    public void Test1()
    {
        Helper h = new Helper();
    }

**NLog version**: 
4.4.12

**Platform**:  .Net 4.5 / .NET Core

**Comment by snakefoot** [comment]
The exceptions you are seeing is the result of NetStandard2.0 trying to loading a NetFramework4.5-dll, and failing because of API-methods.

There has been a minor delay of one year to adapt to NetCoreApps:

http://nlog-project.org/2017/12/20/nlog-4-5-is-near.html

While waiting for the final release of NLog 4.5 RTM, then you have to play with release-candidates:

https://www.nuget.org/packages/NLog/4.5.0-rc04

It will work with your NetCoreApp without any extra dependencies or funny exceptions (also very stable)

**Comment by acidos** [comment]
Indeed, it works like a charm! 
Thanks a lot!

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
