### ISSUE TITLE
No performance improvement on passing argument to the log method

### ISSUE THREAD

**Issue by Havoc9792** [NLog/NLog#3006]
I have a question on logging with formatted string vs passing argument as mentioned at https://github.com/NLog/NLog/wiki/performance

NLog version: 4.5.10

Platform: .Net 4.5
```
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	  <targets>
	    <target name="file" xsi:type="AsyncWrapper" timeToSleepBetweenBatches="0" overflowAction="Block">
	      <target type="File" layout="${longdate} ${level:uppercase=true} ${logger} ${message} ${onexception:EXCEPTION OCCURRED\:${exception:format=ToString,StackTrace} ${newline}}" fileName="C:\temp\Service-${environment:username}-${machinename}-${processid}-${shortdate}.log" archiveFileName="C:\temp\log.${shortdate}.{#####}.txt" archiveAboveSize="10240000" archiveNumbering="Sequence" encoding="iso-8859-2"/>
	    </target>
	  </targets>
		<rules>
			<logger name="*" minlevel="Info" writeTo="file"/>
		</rules>
	</nlog>
```

```
logger.log(LogLevel.Info,"Ric {0} Acct : {1} ParentAcct : {2} Pos : {3} SodPos : {4} Bot : {5} Sold : {6}", Sym, Acct, ParentAcct, Position, SodPosition, BuyDone, LongSellDone + ShortSellDone);

logger.log(LogLevel.Info,$"Ric {Sym} Acct : {Acct} ParentAcct : {ParentAcct} Pos : {Position} SodPos : {SodPosition} Bot : {BuyDone} Sold : {LongSellDone + ShortSellDone}");
```
In dotTrace they seem to have no difference. Time taken at LogEventInfo.CalcFormattedMessage in (1) is the same as time taken in String.Format in (2). Both on the main thread. Am I missing something?

**Comment by snakefoot** [comment]
Like all performance optimizations then they focus on certain code-paths, so one needs to stay on the right code-path to get the performance. Usually there are certain restrictions for staying on the code-path for optimal performance. 

The goal is to defer the message-formatting so it becomes async. The async message-formatting requires that all parameters are immutable. To ensure that they don't change after having called the Logger (Ex logging an object and disposing the object afterwards should not log a disposed object).

- The NLog Logger checks whether all parameters are immutable / primitive. If one is complex-object, then message-formatting is not deferred.
- When having more than 5 parameters then it will skip the performance optimization, because checking the immutable state of the parameters has a cost.

But the most obvious performance optimization happens when logging something that is not needed. If you let NLog do the formatting of the string. Then it will only happen if the LogLevel matches a Target. If no configured NLog targets, then the Logger-call has no cost.  But if you do the formatting upfront before doing the Logger-call, then it always has a cost.

**Comment by 304NotModified** [comment]
> Both on the main thread. Am I missing something?

At least there is a benefit when turning off the logging rule :)

**Comment by 304NotModified** [comment]
Feel free to edit the wiki :)
