### ISSUE TITLE
KeepVariablesOnReload not work, runtime Variables is reset

### ISSUE THREAD

**Issue by SanteR1** [NLog/NLog#3304]
NLog version**: 4.6.2
NLog.Web.AspNetCore  version**: 4.8.1
NLog.Extensions.Logging version**: 1.4.0

**Platform**: .NET Core 2.2.2

**Current NLog config** : [config](https://gist.github.com/SanteR1/7fc8429c83543b4bd4fc8a2b3a14db12)

```
var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();// this 0 variables
LogManager.Configuration.Variables["mydir"] = env.ContentRootPath;
//after add 1 variables
logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger(); //after, 0 variables, why reset?
```

**Comment by snakefoot** [comment]
As the name says `KeepVariablesOnReload` then it means it will keep dynamically configured NLog Variables when used together with `AutoReload="true"`.

It does not mean it will restore NLog variables when replacing LoggingConfiguration with a whole new config.

I suggest that you instead use `${gdc}` instead of NLog variables:

https://github.com/NLog/NLog/wiki/Gdc-layout-renderer

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
