### ISSUE TITLE
FallbackGroup doesn't support batch writes

### ISSUE THREAD

**Issue by ALFNeT** [NLog/NLog#3352]
This might be by design but it looks like when using the FallbackGroup wrapper, all write operations in the wrapped target happen individually regardless of them implementing `Write(IList<AsyncLogEventInfo> logEvents)`. 

For a bit of context about why this is an issue, I'm currently trying to create a target for Amazon Kinesis Firehose, as a way to reduce costs and increase throughput the Firehose SDK/API exposes a bulk put operation. 
The extension is working well but for my current use case I wanted to make sure not to loose events due to network issues, service disruptions, etc. So I set it up using a fallbackGroup wrapper like so:

```
<targets>
    <default-wrapper xsi:type="AsyncWrapper" overflowAction="Grow" queueLimit="15000" timeToSleepBetweenBatches="0" batchSize="200" />
    <target xsi:type="FallbackGroup" name="fallback-group" returnToFirstOnSuccess="true">
        <target xsi:type="CircuitBreakerWrapper" timeout="30" failureThreshold="2">
            <target xsi:type="KinesisFirehose" name="firehose" deliveryStreamName="${mdlc:item=FirhoseStreamName}" layout="${message}" />
        </target>
        <target xsi:type="File"
            name="fallback"
            layout="${message}"
            fileName="${mdlc:item=RootDir}\fallback-current-${machinename}.txt"
            archiveFileName="${mdlc:item=RootDir}\fallback-${date:universalTime=True:format=yyyyMMddHH}-{#}-${machinename}.txt"
            archiveEvery="Hour"
            archiveNumbering="Sequence"
            encoding="utf-8"
            />
    </target>
</targets>
```

Is there a workaround for this behavior? Or plans to support bulk writes?

Cheers!

**Comment by snakefoot** [comment]
Think you can get what you want by doing it the following order:

- FallbackWrapper
   - AsyncWrapper  / BufferingWrapper
      - FinalTarget

NLog 4.6.3 add several improvements to a new base-class called AsyncTaskTarget that implements Batching/Recovery/Retry-logic:

https://github.com/NLog/NLog/wiki/How-to-write-a-custom-async-target

**Comment by ALFNeT** [comment]
Oh nice! I've tried that work around and it worked as expected.

One question before closing this, I hadn't seen it before and it looks like it might be the right thing to use going forward, I think the docs look good enough to start working on it but I'm wondering if it's currently being used by any Targets?, can't see any of the shipped ones using it.


btw, thanks heaps for the help @snakefoot!

**Comment by snakefoot** [comment]
Well it would be a breaking change to modify existing NLog targets in the core package.


Also many likes the old style synchrone behavior (when Logger call completes then logevent has been written to target)


But I have seen many new 3rd Party cloud APIs have async interface so this synchrone promise is no longer possible.


And especially for cloud APIs then there is a strong wish for doing batching because of high latency along with possible downtime with need for retry.


But it is a chicken and egg problem with introducing AsyncTaskTarget. Need battleground experience before people will adopt it. But it will not get this pressure testing before people adopt it.


Had the same issue when I created TargetWithContext where I had to manually implement many NLog targets in my spare time (ex for Google Stackdriver). It is actually the experience learned from Google stackdriver that lead me to work on AsyncTaskTarget.


Sent from my Sony Xperia


---- Alan Featherston Lago wrote ----


Oh nice! I've tried that work around and it worked as expected.

One question before closing this, I hadn't seen it before and it looks like it might be the right thing to use going forward, I think the docs look good enough to start working on it but I'm wondering if it's currently being used by any Targets?, can't see any of the shipped ones using it.

btw, thanks heaps for the help @snakefoot<https://github.com/snakefoot>!

**Comment by ALFNeT** [comment]
Thanks for the reply, you are absolutely right about cloud API, that's exactly my use case right now, I'll see how far I can get with this.

Once again you've been super helpful, closing this Issue now.

Cheers!

**Comment by 304NotModified** [comment]
> Well it would be a breaking change to modify existing NLog targets in the core package.

Maybe another option is to create another target next to it.

**Comment by snakefoot** [comment]
I guess a new HttpClient target could be created with builtin support for batching.


Just need a Champion. Sadly still a shortage of those


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Well it would be a breaking change to modify existing NLog targets in the core package.

Maybe another option is to create another target next to it.
