### ISSUE TITLE
Missing documentation on rules for NLog.config

### ISSUE THREAD

**Issue by mindisk** [NLog/NLog#3377]
I was looking at how to configure logger rules in NLog.config. I wanted to add a name (identifier) to rule. I tried following [Rules](https://github.com/nlog/NLog/wiki/Configuration-file#rules) section and I got confused about how to assign this name to a rule. 
After digging through the code I found a property named *RuleName*. It was not clear from the wiki how this property is assign using `<logger>` tag. I found out that this tag does not support such attribute.  You need to use `<rule>`  tag within  `<rules>` . There was no information in the wiki about this `<rule>` tag and difference between it and the `<logger>` tag.<br />
Example:
`<logger name="*" minlevel="Info" writeTo="defaultlogfile" />`
`<rule name="defaultlogfile" logger="*" minlevel="Info" writeTo="defaultlogfile"/>` 

I am not sure if these two tags can be used simultaneously pointing to different targets. 

All in all, I would ask to update the wiki about `<rule>` tag and the difference between it and the `<logger>`  (if this information is not located in some other place already).

**Comment by snakefoot** [comment]
I created #2891 to resolve  #2394, so I could use it for NLog-config in appsettings.json.

Sadly enough the `<logger>`-tag uses the attribute `name=`, and telling everyone that they now should use `<rule>` just incase they wanted to give their logging-rules an identifier sounded like hard work without any winners.

So I settled for it being an easter-egg for those who need to fiddle with their logging-rules at runtime through code instead of nlog.config.

You are welcome to make a PR makes it possible to do this `<logger name="..." rulename="123" />`, and then make a nice Wiki-page about it.

**Comment by 304NotModified** [comment]
There was a mistake in the docs I see:

![image](https://user-images.githubusercontent.com/5808377/58054920-744e3180-7b5c-11e9-94c5-ac764b78d7b3.png)

fixed it:

![image](https://user-images.githubusercontent.com/5808377/58054973-a19adf80-7b5c-11e9-8c31-08d629af15f2.png)

I will also update the XSD

**Comment by 304NotModified** [comment]
OK I have to check what is now implemented. Not what I had in mind...

**Comment by 304NotModified** [comment]
fixed now:

![image](https://user-images.githubusercontent.com/5808377/58505078-64ea6c00-818c-11e9-97b2-34d0c4cdf9e6.png)

https://github.com/NLog/NLog/wiki/Configuration-file

**Comment by 304NotModified** [comment]
thanks for reporting!
