### ISSUE TITLE
Add Logger.SetGlobalContext, SetThreadContext/WithThreadContext etc 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3427]
Add Logger.AddGlobalContext(string, object) etc to Logger

I think a LoggerExtensions should be nice for this.

**Comment by 304NotModified** [comment]
or GlobalProperty?

**Comment by snakefoot** [comment]
Like the extension-method idea for AddThreadContext. Since they will not live on the Logger-object.

Would be even better if the GDC-dictionary lived on the LogFactory, so one could have multiple global-variable-collection. But that is for NLog 5.0

**Comment by snakefoot** [comment]
Maybe have it as `WithThreadContext` (using-scope) and `SetThreadContext` (override existing value)

**Comment by 304NotModified** [comment]
sounds good :)

**Comment by snakefoot** [comment]
Maybe make these helper methods extensions method on the ILogger-interface. Since they will not change the Logger-object.

Maybe skip the `Thread`-word since they can also follow the `Task`. Maybe just call them `PushContext`  (Calls MappedDiagnosticsLogicalContext.SetScoped)  and `SetContext` (Calls MappedDiagnosticsLogicalContext.Set)

**Comment by snakefoot** [comment]
Resolved by #4213 (Adding `Logger.PushScopeProperty` + `Logger.PushScopeState`)
