### ISSUE TITLE
Use case for RandomizeGroup Target

### ISSUE THREAD

**Issue by wehadfun** [NLog/NLog#3552]
What is the use case for RandomizeGroup target?

**Comment by snakefoot** [comment]
Have never used it myself, and nothing interesting turns up when asking google.

But lets make this the sunday challenge. Here is one idea:

- Have an old issue tracking application, that you would like to add email notification when issue is created.
- Instead of sending email to all developers then just send an email to a single developer that should pickup the issue.
- Hook up a NLog logging to the issue-created logevent and then configure a list of email-targets to the different developers.
- Wrap all the email-targets in a RandomizeGroup-target.

Anyway you are not forced to use all features of NLog :)
