### ISSUE TITLE
Static class having Logger object errors out.

### ISSUE THREAD

**Issue by Rajkumar28269** [NLog/NLog#3702]
I have a project which has static class and I need Logger object to be created and all the methods use the logger object. Do we have any work around for this scenario.

**Comment by snakefoot** [comment]
You mean like this:

```
static class HelloClass
{
    static readonly NLog.Logger Log = NLog.LogManager.GetCurrentClassLogger();

    static void HelloMethod()
    {
         Log.Info("Hello World");
    }
}
```

**Comment by Rajkumar28269** [comment]
You are correct. I tried this in console project and got compile time error in console project. Also i tried this in my wrapper classes and got run time error.

**Comment by snakefoot** [comment]
You need to give some better feedback.


- The exact compiler error along with source code.

- The exact runtime exception with calls tack that fails.


Remember no one is sitting next to you and can see what happens on your screen


Sent from my Sony Xperia


---- Rajkumar28269 wrote ----


You are correct. I tried this in console project and got compile time error in console project. Also i tried this in my wrapper classes and got run time error.

**Comment by Rajkumar28269** [comment]
I am sorry. I was able to find the error. It is not with static classes but the issue is with string or binary data in logeventinfo parameter.
LogEventInfo theEvent = new LogEventInfo(LogLevel.Trace, logger.Name, logMessage);

In the above the variable logMessage that is being passed has more than 300 characters and its failling. I overlooked as if my static class logging methods are failing. But can you let me know what is the maximum characters that are allowed for parameter message in LogEventInfo class.

**Comment by snakefoot** [comment]
Think the max is 2 gigabyte. But there might be limitations depending on the NLog Targets in use.


Sent from my Sony Xperia


---- Rajkumar28269 wrote ----


I am sorry. I was able to find the error. It is not with static classes but the issue is with string or binary data in logeventinfo parameter.
LogEventInfo theEvent = new LogEventInfo(LogLevel.Trace, logger.Name, logMessage);

In the above the variable logMessage that is being passed has more than 300 characters and its failling. I overlooked as if my static class logging methods are failing. But can you let me know what is the maximum characters that are allowed for parameter message in LogEventInfo class.

**Comment by Rajkumar28269** [comment]
May I know the limitation for SQL Server target.

**Comment by snakefoot** [comment]
Depends on the type used for the database column. But there are also default limits in sql-server:


https://stackoverflow.com/questions/4833549/nvarcharmax-still-being-truncated


Btw. It seems that your original question is no where near what we are talking about now. Remember that stackoverflow is a great resource if you care to look


Sent from my Sony Xperia


---- Rajkumar28269 wrote ----


May I know the limitation for SQL Server target.

**Comment by Rajkumar28269** [comment]
ok got you. Thanks for guiding me and have a great day :) You can close the request.
