### ISSUE TITLE
How to log fullname of level, like "Information" instead of "Info"

### ISSUE THREAD

**Issue by geedsen** [NLog/NLog#3710]
How to log fullname of level, like "Information" instead of "Info". Our current implementation is that we added a Sumologic provider directly to the Microsoft logging extensions.  What we see here is that the levels are logged as "Warning" and "Information". We now try to move to Nlog with a SumologicTarget. Everything works except for the level. Nlog abbreviates them to "Warn" and "Info". I tried using ${level:format=Name}, but that still uses the abbreviation. Anyway of accomplishing this without completely needing to write a custom renderer?

**Comment by snakefoot** [comment]
Think it is a good idea to extend NLog ${level} renderer to show full-name. Though it might not work completely since there is also MEL-Critical (Matches NLog Fatal):

But you can use the dark-magic in NLog to create your own custom layout-renderer:

```xml
  <variables>
    <variable name="FullLevel" value="${level:when=level!=LogLevel.Info and level!=LogLevel.Warn and level != LogLevel.Fatal}${when:when=level==LogLevel.Info:inner=Information}${when:when=level==LogLevel.Warn:inner=Warning}${when:when=level==LogLevel.Fatal:inner=Critical}" />
  </variables>
  <targets>
    <target xsi:type="Console" name="consoleTarget" layout="${date}|${FullLevel}|${message}" />
  </targets>
```

Notice how the NLog-config-variable `${fulllevel}` converts from NLog-LogLevel to MEL-LogLevel, and then can be reference in other layouts.

**Comment by snakefoot** [comment]
@geedsen Created  #3713 that introduce the Format=FullName for `${level}`

**Comment by geedsen** [comment]
Thanks for reacting so fast. The custom renderer is already working now. But it impressive to see how fast issues actually lead to solutions. Thanks for the help.
