### ISSUE TITLE
UseNLog vs AddNLog 

### ISSUE THREAD

**Issue by povstyany** [NLog/NLog#3759]
I'm trying to figure out what's the difference between such registrations of NLog:

One:

           WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>()
            .ConfigureLogging(logging =>
            {
                logging.ClearProviders();
                logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
            })
            .UseNLog();

Two:

            WebHost.CreateDefaultBuilder(args)
            .ConfigureLogging(
                logging =>
                {
                    logging.ClearProviders();
                    logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
                    logging.AddNLog("path");
                }
            );

According to doc I should use first one. For both cases I tried to check how services registered, and when instances are added to service collection, but didn't found the answer. Could you please explain why first one is recommened and what is the defference between registrations?

**Comment by snakefoot** [comment]
Originally the `AddNLog` was only available for `ILoggerFactory`, which only registered NLog as LoggingProvider. But FAILED to hook up all the [`${aspnet}`](https://nlog-project.org/config/?tab=layout-renderers&search=package:nlog.web.aspnetcore)-layoutrenderers.

To correctly register NLog as LoggingProvider AND hook up `${aspnet}`-layoutrenderers. Then one had to call `UseNLog()`.

Later in time then `ILoggingBuilder` was introduced with AspNetCoreV2. This suddenly allowed `AddNLog` to also work correctly like `UseNLog` (Because `ILoggingBuilder` gave access to the dependency injection system).

With NLog.Web.AspNetCore ver. 4.0 then both both `ILoggingBuilder.AddNLog` and `IHostBuilder.UseNLog` will work just fine. So now it is up to the user which style feels right.

**Comment by povstyany** [comment]
I investigated up to level of BuildCommonServices() execution and found out that same services are registered for both variants. So, my theory is confirmed.

Many thanks, now it's clear
