### ISSUE TITLE
System.Configuration.ConfigurationManager not avaliable in .Net Core 3.0 and above

### ISSUE THREAD

**Issue by RichardPetheram** [NLog/NLog#3802]
NLog version: 4.6.8

I've been trying to port a desktop app to .Net Core 3.1, but any reference to LogManager.Configuration produces a message that the ConfigurationManager assembly cannot be loaded. Is there a work-around for this?

Note, this is currently a multi-targetted library project, the .Net 4.7.2 target works just fine.

**Comment by 304NotModified** [comment]
I never have seen this error. 

What platform build do you use? Please share the properties of the NLog.dll  - go to the NLog.dll in your bin folder in explorer. Go to properties and please share a screenshot of the details tab.

**Comment by RichardPetheram** [comment]
Properties as requested.

![NLog_Details](https://user-images.githubusercontent.com/36625136/74099055-5fb12f80-4b17-11ea-9937-611447464d1e.PNG)

Curiously, the installed version reports 4.6.8

![image](https://user-images.githubusercontent.com/36625136/74099134-5aa0b000-4b18-11ea-9135-ec38b508d53a.png)

**Comment by snakefoot** [comment]
Sounds like you have multiple projects:

- trying to port a desktop app to .Net Core 3.1
- This is currently a multi-targeted library project,

Make sure to change all libraries to use Net Core 3.1 and not just some of them. And ensure that their dependencies are also supporting Net Core 3.1

Make sure that none of the libraries in this chain suddenly have a direct reference (or hintpath) to the NLog.dll, but all of them are using nuget-packages (Change projects to newstyle using `<packagereferences>`)

NetCore31 will try to be optimistic, so if it meets a library that only supports NetFramework, then it will load it anyway. If that library references NLog.dll for Net45 then you will get an error.

Anyway have no issue with using NLog with multitarget applications, so I think the problem is in your application.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
