### ISSUE TITLE
Documentation mixes rules/logger/@minlevel and @minLevel

### ISSUE THREAD

**Issue by aliquid** [NLog/NLog#3822]
Documentation states `minlevel` (lower-case) but gives some odd examples with `minLevel` (camel-case); https://github.com/nlog/nlog/wiki/Configuration-file#rules

Examples in repo (*.xml) have many occurrences of the lower-case `minlevel` but one (namely `examples/NLogReceiverService/NLog.config`) of the camel-case `minLevel`.

Test cases in the repository (*.cs) have a mix of lower-case and camel-case but at least some look intentional (e.g. `DuplicateConfigurationAttributeTests`).

XML as such is sensitive to case, and even though it might seem parsing of NLog configuration is laxed in that aspect, I would argue that documentation and examples should still be strict.

**Comment by snakefoot** [comment]
@aliquid These unfortunate inconsistencies in documentation are not caused by people trying to perform terrorism against people with OCD.

Can only agree that documentation and example should stay on the strict path, that doesn't generate XSD-schema-validation warnings / errors.

But because the documentation is free for editing and the NLog community cannot afford a professional technical writer, then it is currently best-effort approach.

If you have some spare time on your hands (And I guess you do since you had time for creating this issue). Then you are welcome to polish away the most aggravating mistakes. 

Have now updated the Wiki-page for you :)

**Comment by aliquid** [comment]
Lol. After battling with configuration last few days, I am now beginning to feel comfortable making the calls necessary to update documentation in the future. :-)
