### ISSUE TITLE
Automatic AutoLoadAssemblies in the last version of NLog not mentioned in Release details

### ISSUE THREAD

**Issue by ilya-spv** [NLog/NLog#3875]
**NLog version**: 4.7

**Platform**: .NET Core 3

I have the following code that I need for the AspNetCore extension to work (I have programmatic config):

```
var assembly = Assembly.Load("NLog.Web.AspNetCore");
    ConfigurationItemFactory.Default.RegisterItemsFromAssembly(assembly);
```

I have tried to do this in the latest NLog version:

```
    LogManager
                .Setup()
                .SetupExtensions(e => e.AutoLoadAssemblies(true));
```

I have figured out that everything seems to work out of the box without this code. I guess auto loading was turned on somewhere but I did not see any mention of that in the changelog/release log.

If I got it right and that is the case, it is probably worth mentioning somewhere?

**Comment by snakefoot** [comment]
`AutoLoadAssemblies` is actually turned on by default, and it doesn't work very well with nuget-packages. So actually the intention is that one should do this:

```c#
    LogManager.Setup()
                .SetupExtensions(e => e.AutoLoadAssemblies(false).RegisterAssembly("NLog.Web.AspNetCore"));
```

When https://github.com/NLog/NLog.Web/pull/540 has been merged, then you can do this:

```c#
    LogManager.Setup()
                .SetupExtensions(e => e.AutoLoadAssemblies(false).RegisterNLogWeb());
```

**Comment by ilya-spv** [comment]
Sounds very good, thanks for the advice! I will switch to registering the assembly explicitly. If you mean this is a security issues it's probably best to turn it off by default perhaps and provide a clear example on how to do it?

Like the one you just posted here

**Comment by snakefoot** [comment]
Well right now AutoLoadAssemblies is a feature that has been in NLog for a long time, and many old NetFramework applications depend on it.


Changing default behavior requires major version bump (breaking change) . Which is why the change is delayed until NLog 5.0


Also one have been able to disable the feature  for a long time. Now just implemented a simpler way to disable it while waiting for NLog5


No one is stopping you from improving the wiki pages for NLog. Have discovered that my personal preferences are not always the same for others.


Sent from my Sony Xperia


---- Ilya Chernomordik wrote ----


Sounds very good, thanks for the advice! I will switch to registering the assembly explicitly. If you mean this is a security issues it's probably best to turn it off by default perhaps and provide a clear example on how to do it?

Like the one you just posted here

**Comment by ilya-spv** [comment]
Thanks for help! I guess I can just close this issue

**Comment by snakefoot** [comment]
Have updated the Wiki for you:

https://github.com/NLog/NLog/wiki/Configure-from-code#logfactory-initial-setup

**Comment by ilya-spv** [comment]
Thanks, looks great!
