### ISSUE TITLE
WhenRepeatedFilter filtering out logs that are not similar and only output one

### ISSUE THREAD

**Issue by Azagatoth** [NLog/NLog#3892]
Type:
Bug

NLog version:
4.7.0

Platform:
.NET 4.7.2

I wanted to test the WhenRepeatedFilter as it sounded exactly like the filter I was looking for.
There might be something I have missed, but it seems to be bugged?
I wrote a very small test case to see if I could use the filter (see screenshot)

![NLog program](https://user-images.githubusercontent.com/34308240/79198613-0a094400-7e34-11ea-8373-ab7254f250f8.png)

As you can see in the screenshot, the second error log only came out once and with the wrong "hit count"
After the initial log of it, it does not seem to be logged anymore?

**Comment by snakefoot** [comment]
My eyes does not see well, but it look like you are assigning Layout to static string `CsvLayout`:

```c#
var whenRepeated = new WhenRepeatedFilter
{
    Layout = "CsvLayout"
}
```

`WhenRepeatedFilter` checks the output rendered by Layout and compares to previous result. When using a static string, then the output rendered is always the same.

Can you explain what you expect should be happening?

**Comment by Azagatoth** [comment]
@snakefoot Forgive my ignorance, but I thought this would use the "CsvLayout" layout that is shipped with NLog. As you can see from the screenshot I actually get one line with the second log?

**Comment by snakefoot** [comment]
When using the CsvLayout, then you need to make an instance of the CsvLayout-class and configure it:

https://nlog-project.org/documentation/v4.7.0/html/T_NLog_Layouts_CsvLayout.htm
https://nlog-project.org/documentation/v4.7.0/html/T_NLog_Layouts_CsvColumn.htm

Btw. it is not very optimal to use CsvLayout as filtering-logic. Can you explain why CsvLayout would be good to use as filter in `WhenRepeatedFilter` ?

Usually one would use this as filter:

```c#
var whenRepeated = new WhenRepeatedFilter()
{
     Layout = "${message}${exception:format=Type,Message}";
     Action = FilterResult.Ignore,
     TimeoutSeconds = 5,
}
```

**Comment by Azagatoth** [comment]
It was a simple sample, not production code :-)

If I do this:
            var layout = new CsvLayout();
            var whenRepFilter = new WhenRepeatedFilter
            {
                TimeoutSeconds = 5, Action = FilterResult.Ignore, FilterCountMessageAppendFormat = " (Hits: {0})", Layout = layout
            };

I get the same result as before, but if I use your layout string it works fine.
It might just be something I am not comprehending.

**Comment by snakefoot** [comment]
A newly created CsvLayout without any columns will not generate any output. So again you have just configured a static-string. Now `""` instead of `"CsvLayout"`.

Happy to hear my example is working. Can you explain why CsvLayout would be good to use as filter in WhenRepeatedFilter ?

**Comment by Azagatoth** [comment]
@snakefoot As I mentioned above, this was just a very fast put together sample to see if the WhenRepeatedFilter would be able to solve log spamming.
In our real environment there is already a proper layout.

Regards from a fellow dane :-)

**Comment by snakefoot** [comment]
Little strange  you create a bug report about NLog feature not working, but have skipped the actually configuration. And then say it is because it is "not production code".

The best way to avoid log spamming is not to do log-spamming. Don't spend time on logging stuff that is not needed. NLog `WhenRepeatedFilter` is intended for actual end-users (not application developers), so they can work-around a broken application (application developers can fix the application logging).

I think it is bad idea to use `CsvLayout` as your Layout-filter, since it spends a lot of time of formatting and correctness (Honor the Csv standard). All that validation work is only needed when writing to an actual output target (Filtering doesn't care about correctness). Filtering only cares about uniqueness.

Anyway happy you got `WhenRepeatedFilter` working, after you gave it a Layout that actually reacted and didn't produce static output. Held og lykke med dit nye kode eventyr :)

**Comment by Azagatoth** [comment]
Yea, it should have been a question, my bad.

I totally agree that logging should not be spammed, but having 50+ people across many teams working on the same product and not all know how to properly log, then something like this is needed until there is a general agreement about logging only being ment for spotting errors.

Please understand that the csv logging was me being lazy in this sample and not providing a proper layout :-)
