### ISSUE TITLE
Create log file only if there are errors captured?

### ISSUE THREAD

**Issue by sekulicb** [NLog/NLog#4104]
Hi,

Is there an option to set the target as filename, but only create a log file for that day, if there are errors. Right now if I set in the config:

```xml
 <target xsi:type="File" name="f" fileName="${specialfolder:LocalApplicationData}\MyApp\logs\${date:format=dd-MM-yyyy}.json" encoding="utf-8" lineEnding="LF" >
      <layout xsi:type="JsonLayout" includeAllProperties="true">
        <attribute name="level" layout="${level:upperCase=true}"/>
        <attribute name="time" layout="${longdate}"/>
        <attribute name="type" layout="${exception:format=Type}"/>
        <attribute name="message" layout="${exception:format=message}"/>
        <attribute name="stackTrace" layout="${exception:format=ToString,StackTrace}"/>
        <attribute name='innerException' encode='false'>
          <layout xsi:type="JsonLayout">
            <attribute name="type" layout="${exception:format=:innerFormat=Type:MaxInnerExceptionLevel=1:InnerExceptionSeparator=,}"/>
            <attribute name='message' layout="${exception:format=:innerFormat=Message:MaxInnerExceptionLevel=1:InnerExceptionSeparator=,}"/>
            <attribute name='exception' layout="${exception:format=:innerFormat=ToString}"/>
          </layout>
        </attribute>
        <attribute name="account" layout="${windows-identity}" />
      </layout>
    </target>
  </targets>

```

Every time when I start the app for the first time on specific date, I see log file created, which is fine. But it can happen that there are no errors for that date, and then I end up with a bunch of json files which are empty. I just want to be able to have logs but only for the actual days when errors did happen. This way I will not have a bunch of json files sitting on the system. Thanks

**Comment by snakefoot** [comment]
NLog only creates the actual file, when a logevent is routed to the file-target. Very strange that you get an empty file (Since the `JsonLayout` should always generate output with the attributes shown here).

Can you attach a small example project that reproduces this behavior with an empty file?

Or does a bunch of empty json-files, mean json-files that contains json but not any error-events? Maybe use the `AutoFlushWrapper` together with `BufferingWrapper` like shown here (only writes on error-event):

https://github.com/NLog/NLog/wiki/AutoFlushWrapper-target
