### ISSUE TITLE
Deadlock when multiple applications log to the same table

### ISSUE THREAD

**Issue by westner** [NLog/NLog#4294]
Hello,

we have about 100 applications which all logs to the same table in SQL-Server 2017.

We get a lot of deadlock-messages while logging.

The table has no indexes or contraints and is very simple:

```
CREATE TABLE [dbo].[log_system](
	[time_stamp] [datetime] NOT NULL,
	[customername] [nvarchar](255) NOT NULL,
	[url] [ntext] NOT NULL,
	[action] [ntext] NOT NULL,
	[ip] [nvarchar](40) NOT NULL,
	[level] [varchar](20) NOT NULL,
	[message] [ntext] NOT NULL
) 
```

As far as I remember we only have the deadlock-problems since we update our used nlog-assembly to the current version.

Does anybody has an idea how to avoid the deadlocks or what could cause the problem?

Thanks

Stefan

**Comment by snakefoot** [comment]
If you have a deadlock victim when using the database, then you should contact your Database-Administrator (dba), and have them tell you what stored procedures are conflicting.

If you have application deadlock because of lock-objects are taken in the wrong order, then please show some callstacks where different threads are stuck. But if NLog is not part of the callstack, then you probably create an issue somewhere else.

**Comment by snakefoot** [comment]
Btw. you have been here before #4203, are we running in circles?

**Comment by westner** [comment]
Yes, I was there in 4203 before.

After that issue I changed the transisolationlevel, removed the database index on the NLog-Logtable and all worked fine for about two month. Now we updated to the current version of NLog and without changing anything in DB or in our code we have deadlocks again.

I will collect the requested info and post it here.
