### ISSUE TITLE
"Right" way to log exceptions

### ISSUE THREAD

**Issue by MgSam** [NLog/NLog#431]
The onexception and exception layout renderers seem to only do anything if one of the logger methods with "exception" in the name are called. However, those logger methods with "exception" are now deprecated. 

So what is the "right" way to log exceptions now? Passing the exception into one of the normal log methods (Warn(), Error(), Fatal()) does not include the stacktrace as part of the message.

Maybe there should be an onerrororabove layout renderer?

**Comment by fhoeben** [comment]
Having the exception as first parameter would work, but seems to break symmetry with other overloads for logging an exception that take it as last parameter. Would you mark all those as obsolete?

To me giving special meaning to the last argument, in case it is an exception, seems the most logical approach. Asking around in teams I'm involved in confirms that this is what people expect, as do some of the bugs I encounter :-). (I also noticed this is also the approach adopted by the Java logging framework slf4j, http://slf4j.org/faq.html#paramException).

The fact that Resharper (currently) would warn about an argument without placeholder in the message does not mean it should not be done. Resharper is a very good tool, but I believe its warnings/suggestions need to be evaluated by the programmer, not blindly followed. If the logging methods have such meaning for their parameters this might even trigger the Resharper team to create a new annotation or rule to help programmers use it correctly. They aim to assist programmers, not define what can and cannot be done in APIs.

**Comment by 304NotModified** [comment]
Reopen as inspired by #568.  I think this should be solved. I have also seen that some less experienced NLog users have problems to correctly log exceptions.  

I think the solution by @ilya-g (11 dec) Is the best solution.

**Comment by 304NotModified** [comment]
Reshaper is always a guideline, but IMO we have to think twice when Resharper complains.

**Comment by 304NotModified** [comment]
I will create a PR for this.

**Comment by Xharze** [comment]
@304NotModified Could this issue be closed, now that #602 have been merged?

**Comment by 304NotModified** [comment]
Nope. #602 was only a structural change.

**Comment by 304NotModified** [comment]
@ilya-g , @Xharze 

I was working on this, but there is a problem:

```c#
public void Error(Exception exception, [Localizable(false)] string message, params object[] args)`
```

Looks similar to

```c#
  public void Error(IFormatProvider formatProvider, [Localizable(false)] string message, params object[] args)
```
       
because the call 

```
Error(null, "message {0}", 1)
```

now will give a `ambiguous invocation`. 

Any ideas on this?

**Comment by ilya-g** [comment]
The type of the `null` value can be disabmiguated with a cast if needed: `null as Exception` and `null as IFormatProvider`.
I don't expect anyone explicitly passing `null` to `formatProvider` parameter now, since there is an overload without that parameter, which gives the same result.
So I'll stick to the option 1.

**Comment by NightWatchman** [comment]
I've seen the issue where resharper complains about the parameter not being one for the format string due to the other overloads.  At that point resharper didn't appear to even know of the existence of the Error(message, exception) method.

Now however it seems to pick it up properly and doesn't complain about using it but I'm not sure what changed in my environment. That resharper behavior is a large part of what led me down the path of marking the ErrorException(message, exception) methods as obsolete.

I'm in favor of the API being:
Error(formatString, formatParam, ...)
Error(message, exception)

Error(formatString, formatParam, ..., exception) would be nice of course if you follow that vein, but is not a must-have for me.

At any rate I do think the ErrorException(message, exception) methods are rather superfluous.
