### ISSUE TITLE
Exception when trying to load NLog.dll for NetFramework in NetCoreApp

### ISSUE THREAD

**Issue by EricOreg** [NLog/NLog#4387]
I am creating a new .net core (3.1) project. It uses an existing dll built from a .NET framework project, which uses NLog. 

When I run the executable from my .net core project, I got the following error:

The type initializer for 'NLog.Internal.InternalLogger' threw an exception.  ---> System.IO.FileLoadException: Could not load file or assembly  'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral,  PublicKeyToken=cc7b13ffcd2ddd51'.

I tried to install the System.Configuration.ConfigurationManager through NuGet of my .net core project. But the oldest version of the System.Configuration.ConfigurationManager it can find is 4.4.0. 

Any idea how I can get around the problem?

**Comment by snakefoot** [comment]
This place is for NLog bug-reports and feature-requests. Not the support forum of how to create Monster Applications of Doctor Frankenstein. I think you should take a step back and consider one of these paths:

- Because my dependencies are based on .NetFramework, then I will create my application using .NetFramework
- Because my application MUST use .NetCore, then I will update all necessary dependencies to NetStandard2 / NetCore first (or rewrite them myself).

Then I think your name will by sung as being among heroes, instead of being cursed by your fellow programmers that have to support this strange offspring.

But if you really like to hurt yourself, then you could try and download and unzip the NLog-nuget-package. Then you could try and use the NLog.dll from the NetStandard20-folder, and see if you can shoehorn it into silence. Until you meet the next hurdle.

**Comment by snakefoot** [comment]
Closing due to lack of input.
