### ISSUE TITLE
Document the most robust way to handle configuration initialization.

### ISSUE THREAD

**Issue by JasonWorks** [NLog/NLog#4458]
I was working on a Revit plugin and discovered that another plugin was overwriting my configuration.

Most NLog documentation and tutorials describe using an XML file to configure NLog’s targets and rules.  I followed this pattern:
`NLog.LogManager.Configuration = NLog.Config.XmlLoggingConfiguration.CreateFromXmlString(xml);`

This code creates the configuration based on the XML string and resets the running NLog configuration.  NLog documentation and tutorial do not hint at the possibility of conflict with other software also running which uses NLog or even simple multiple instances within the same application.

If another process using NLog was already running within the application, however, our configuration would have overwritten the previous configuration.

### Problems:
- NLog configuration management is not instanced and does not handle multiple processes automatically.
- NLog configuration can be easily overwritten by another process within the same application instance.
- NLog does not provide tutorials, does not document, or even hint to indicate proper (defensive) handling of configuration.

### Solution:
- Document that NLog users should check whether a configuration has already been established and overlay targets and rules.
- Document that NLog users should gracefully handle configuration overwrites by less aware plugins/processes by listening to the related `ConfigurationChagned` event and overlay targets and rules at that time.

### Addendum (Merge API):
As mentioned, nearly all the documentation and tutorials describe using an XML file to configure NLog's targets and rules.  Unfortunately there is no trivial way to merge or overlay XML created configurations.  

If there is a way to trivially overlay such configurations then document it - if not, maybe add that to the API?  

If not, then please provide more documentation on the more robust way to handle configuration initialization and overlays.

**Comment by snakefoot** [comment]
In my world an application is running as a process. You don't have multiple processes within an application. You can launch the same application multiple times each application-instance then runs in their own process.

NLog LoggingConfiguration is often configured for the entire process using the static variable `NLog.LogManager.LogFactory`. This provides a lot of simplicity, and works for 98 pct. of the use-cases.

There are certain applications that supports a plugin-model (or hosting-model like Service-Fabric), that loads external modules into the the application-process. This ofcourse requires the plugins to behave as nice guests in the house, and not starting to replace the carpet in the living room.

For these rare situations where the plugin wants to have its own special NLog LoggingConfiguration, then the plugin can just create its own isolated NLog LogFactory, and leave the global `NLog.LogManger.LogFactory` alone.

Very few a using this mode, so that is probably why you see very few blog-pages/articles about how to use it.

See also: https://github.com/NLog/NLog/wiki/Configure-component-logging

**Comment by JasonWorks** [comment]
Thanks snakefoot!  

Configure-component-logging seems like the correct way to go in this case.  My searches simply didn't pickup on using a different LogFactory as the instancing mechanisms.  And when I perused all the documentation, I did not make the connection to my case in the Configure_component-logging link. 

So my suggestion would be to include additional statements to the Configure_component-logging page about the possible overwriting of configuration targets and rules.

**Comment by JasonWorks** [comment]
I may not have seen this page earlier.

I do not see the link to Configure-component-logging within the index on the right for the wiki page - is it labeled differently?  Where else it the link to that page surfaced?

**Comment by snakefoot** [comment]
For some reason then Google is very bad at indexing the NLog Wiki Pages. So they only appear when searching for keywords part of the actual Url.


Sent from my Sony Xperia


---- JasonWorks wrote ----


I may not have seen this page earlier.

I do not see the link to Configure-component-logging within the index on the right for the wiki page - is it labeled differently? Where else it the link to that page surfaced?

**Comment by snakefoot** [comment]
Closing the issue as answered.
