### ISSUE TITLE
NLog fails silently when using invalid file path.

### ISSUE THREAD

**Issue by ekutukcu** [NLog/NLog#4479]
**NLog version**: 4.7.10

**Platform**: .Net 5.0

**Current NLog config** (xml or C#, if relevant)

```c#
        static void SetupLogging()
        {
            var config = new NLog.Config.LoggingConfiguration();

            var logfile = new NLog.Targets.FileTarget("logfile") { FileName = @"""D:\Temp\Test.txt\"".txt" };

            // Set more detailed exception logging:
            logfile.Layout = "${longdate}|${level:uppercase=true}|${logger}|${message}|${exception:format=tostring}";

            config.AddRule(NLog.LogLevel.Debug, NLog.LogLevel.Fatal, logfile);

            NLog.LogManager.Configuration = config;

            NLog.LogManager.GetCurrentClassLogger().Info("Created Logging Configuration.");
        }
```

- What is the current result?
NLog continue without logging anything and without throwing an exception.
- What is the expected result?
NLog should throw an exception since the log file name specified does not exist.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes, an exception is shown there.
- Please post full exception details (message, stacktrace, inner exceptions)
```
2021-06-29 14:46:27.8101 Error FileTarget(Name=logfile): Failed write to file 'C:\Users\ekutukcu\source\repos\NLogDemo\NLogDemo\bin\Debug\net5.0\"D:\Temp\Test.txt\_.txt'. Exception: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\ekutukcu\source\repos\NLogDemo\NLogDemo\bin\Debug\net5.0\"D:\Temp\Test.txt\_.txt'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at NLog.Internal.FileAppenders.BaseFileAppender.UpdateCreationTime()
   at NLog.Internal.FileAppenders.BaseFileAppender.TryCreateFileStream(Boolean allowFileSharedWriting, Int32 overrideBufferSize)
   at NLog.Internal.FileAppenders.BaseFileAppender.CreateFileStream(Boolean allowFileSharedWriting, Int32 overrideBufferSize)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Write(Byte[] bytes, Int32 offset, Int32 count)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, ArraySegment`1 bytes, Boolean initializedNewFile)
   ```
- Are there any workarounds? no
- Is there a version in which it did work? Did not check.
- Can you help us by writing an unit test? If necessary, I can do this.
[NLogDemo.zip](https://github.com/NLog/NLog/files/6734354/NLogDemo.zip)

**Comment by snakefoot** [comment]
Yes that is the default behavior of NLog. It swallows all its own errors, instead of taking down the entire application.

You can monitor the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) for Error-events to be notified about internal errors inside NLog (You should NOT attempt to log these error using NLog Logger-objects, as it will cause havoc).

One can also configure `ThrowExceptions=true` but it can make NLog take down the entire application on errors (without it being logged). It is only intended for last-resort troubleshooting, when nothing else has worked.

**Comment by ekutukcu** [comment]
This seems very strange, normally it's much better to fail fast so that issues can be diagnosed and solved sooner rather swallowing errors and continuing with an invalid program state. It could also be dangerous as there's the potential for an application to run for weeks with no logging, so that if an error actually does occur it will be much harder to resolve. Anyway, thank you for letting me know about this.

**Comment by snakefoot** [comment]
I always use throwConfigExceptions=true. But in this case it would not help because of the dynamic nature of NLog Layout (It might only generate a correct filename when some GDC variable is ready)


Sent from my Sony Xperia


---- ekutukcu wrote ----


This seems very strange, normally it's much better to fail fast so that issues can be diagnosed and solved sooner rather swallowing errors and continuing with an invalid program state. It could also be dangerous as there's the potential for an application to run for weeks with no logging, so that if an error actually does occur it will be much harder to resolve. Anyway, thank you for letting me know about this.

**Comment by snakefoot** [comment]
But I guess we could add some extra validation when not making use of NLog Layout (which is your case here)


Sent from my Sony Xperia


---- ekutukcu wrote ----


This seems very strange, normally it's much better to fail fast so that issues can be diagnosed and solved sooner rather swallowing errors and continuing with an invalid program state. It could also be dangerous as there's the potential for an application to run for weeks with no logging, so that if an error actually does occur it will be much harder to resolve. Anyway, thank you for letting me know about this.

**Comment by ekutukcu** [comment]
That might help avoid this issue. It might be better to try and log it's own errors if there are any targets that do manage to get setup correctly (don't know if it is already doing this). Anyway, I'll close this as it's the expected behaviour.

**Comment by snakefoot** [comment]
Created PullRequest #4481 so `ThrowConfigExceptions=true` will take down the entire application.
