### ISSUE TITLE
Microsoft ILogger default Loglevel = Warning and NLog 5.0 gives debug-output

### ISSUE THREAD

**Issue by ynanech** [NLog/NLog#4771]
.net core 6

`"Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }`

I use the NLog default configuratio
The default log level is set to warning, but you can still output information and debug information
Why

**Comment by snakefoot** [comment]
What NLog-version are being used?

**Comment by ynanech** [comment]
![QQ截图20220122095303](https://user-images.githubusercontent.com/20282409/150620294-fd880f80-3b21-41f8-a5c9-3f163b575e03.jpg)

**Comment by snakefoot** [comment]
Yes with NLog 5.0 then Microsoft LoggerFactory filters are disabled by default, because new users was often confused by having 2 log-filtering-configurations (Microsoft + NLog). Many users changing from .NET Framework to .NET Core (with LoggerFactory) expected that NLog-configuration should always "win".

You can revert this [breaking change](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#nlogextensionslogging-without-any-filter) by specifying `RemoveLoggerFactoryFilter = false`. Ex:

```.UseNLog(new NLogAspNetCoreOptions() { RemoveLoggerFactoryFilter = false });```

NLog.config has the following option that works just like Logging.LogLevel.Default = Warning :

```xml
<rules>
    <logger name="*" finalMinLevel="Warn" />   <!--- Suppress all output with severity less than Warning -->
</rules>
```

**Comment by ynanech** [comment]
I see. I prefer the old behavior. Thank you

**Comment by snakefoot** [comment]
Yes I recognize that there are 2 camps:
1. Those who knows about LoggerFactory filtering, and the appsettings-environment-override-capabilities. And how it can be used together with NLog.config.
2. Those who only knows about NLog.config

I was guessing the first group would easily adapt to the changes, since they are probably expert-users.

**Comment by snakefoot** [comment]
Closing question as resolved, due to inactivity
