### ISSUE TITLE
Does NLog have flood protection?

### ISSUE THREAD

**Issue by theREALdebater** [NLog/NLog#4793]
Does NLog have flood protection?

There are various scenarios where the rate of events to be logged becomes too high.

Too high will, of course, depend on circumstances, but in most cases there will be a threshhold of system resource usage (CPU, memory, buses, disks, etc.) beyond which logging should not go. One nighmare scenario is when a piece of exception logging code throws an exception that it ends up trying to handle, resulting in an infinite, uncontrolled loop generating events at an extremely high rate. 

I would kinda expect a logging package such as NLog to have some in-built protection mechanism against flooding, but I see nothing in the documentation.

If NLog doesn't have any flood protection, then I suggest it should become a feature request. 

I've seen that, with the use of batches (and async logging?), events can be dropped. That's good, but there's a lot more to flood protection than that. It is not an easy or trivial piece of functionality to get right.

**Comment by snakefoot** [comment]
I could understand if the logging framework was the agressor that initiated the logging, then it would be natural that the logging framework was introducing the throttle-/backoff-algorithm.

But since the aggressive logging is just a sifde-effect of the actual issue, then I think the actual issue should be handled, instead of trying to protect against some of the symptoms. I guess other symptoms could be overloading service-communication-infrastructure (ex. cloud-network-traffic) or spinning up many instances (ex. cloud-cpu-usage), thus causing expensive bills from the cloud-provider (independent of the amount of logging). 

I could also guess an evil loop could be created without involving any logging, that caused both infrastructure and cpu-usage to sky-rocket, and it would be impossible for logging-framework to prevent this, since not involved in the loop.

**Comment by snakefoot** [comment]
Closing as answered, due to inactivity.
