### ISSUE TITLE
Hundreds ArgumentException thrown for Blazor server app

### ISSUE THREAD

**Issue by Apskaita5** [NLog/NLog#5048]
**NLog version**: (e.g. 4.4.13)

NLog.Web.AspNetCore 5.1.2

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Xamarin Android / Xamarin iOS / .NET Core / .NET5 / .NET6

.NET5, Blazor server app, test solution attached

**Current NLog config** (xml or C#, if relevant)
attached with the test solution

- What is the current result?

1. Create a new Blazor server app solution for .NET5 using MS standard template (I'm using VS 2019 community 16.11.11, though its hardly of importance);
2. Add NLog precisely as described https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-5
3. Start debug and get hundreds of ArgumentException (subject to exception settings the VS will brake on exception or place it to the output window).

- What is the expected result?

No exceptions :)

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

Yes, no errors.
[BlazorNLogTest.zip](https://github.com/NLog/NLog/files/9468556/BlazorNLogTest.zip)
[BlazorNLogTest.zip](https://github.com/NLog/NLog/files/9468561/BlazorNLogTest.zip)

- Please post full exception details (message, stacktrace, inner exceptions)

System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added. Key: ParentComponentId
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key) in /_/src/libraries/System.Private.CoreLib/src/System/ThrowHelper.cs:line 187

- Are there any workarounds? yes/no

no

- Is there a version in which it did work? 

haven't  tried old versions

- Can you help us by writing an unit test?

test project attached

**Comment by snakefoot** [comment]
I'm sorry that you are not getting the expected result, but this repository is for the NLog-core-project, and I don't see anything in the Exception details that points to NLog..

I don't have any experience with Blazor applications, so I think you will get a better response if you post your Question at StackOverflow or Ask Microsoft or try Google.

**Comment by Apskaita5** [comment]
C'mon the show starts on blank MS template exactly after the NLog is installed... (and ends exactly after NLog removal)
I understand that th stack trace is less than informative however it's the NLog issue.
It absolutely prevents using NLog current version at least on Blazor server app, probably for other .NET 5 project types as well.

**Comment by snakefoot** [comment]
Ok you convinced me. I downloaded your example project. Loaded it up in VS2022. Changed the Debug-Exception-Settings to halt on every exception. Changed from IIS Express to just the application. Built and ran the application and my web-browser opened and showed me a web-page asking me: `"How is Blazor working for you?"`

And the application console window displayed the following:
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\myuser\source\repos\BlazorNLogTest\BlazorNLogTest
```
The debugger never stopped because of exceptions.

**Comment by snakefoot** [comment]
Closing the question, due to inactivity.

**Comment by gayaK** [comment]
@Apskaita5 @snakefoot 

This problem is caused by an incorrect log message from ASP.NET Core. 
The issue with the log message has already been fixed in versions .NET7.x and .NET 8.x.
Additionally, it will be fixed in .NET6.0.27. 

Please check my pull request for ASP.NET Core.
https://github.com/dotnet/aspnetcore/pull/53009#issuecomment-1878980721

However, I think [NLog.Internal.PropertiesDictionary.InsertMessagePropertiesIntoEmptyDictionary](https://github.com/NLog/NLog/blob/f586f1341c46fa38aaaff4c641e7f0fa7e813943/src/NLog/Internal/Collections/PropertiesDictionary.cs#L429-L431) whould use `TryAdd` instead of  `Add` .
Because_ performance will be reduced when users make the same mistakes.

**Comment by snakefoot** [comment]
>  Use `TryAdd` instead of `Add` to avoid `ArgumentException `. Because performance will be reduced when users make the same mistakes.

Well I was hoping that the first-chance-exception would developers to fix the faulty logging. Just like NLog throws first-chance exception number of place-holders doesn't match the format-args.

But yes surprised that Microsoft doesn't have tooling to detect invalid format-strings in their source-code on build. Since errors on their side gives a lot of pain, and it takes time to get fixes released.
