### ISSUE TITLE
Feature request: adding parameter type to database target parameters

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#522]
Feature request,

adding parameter type to parameters of [Database target](https://github.com/NLog/NLog/wiki/Database-target). Example:

``` xml
 <parameter layout="Layout" name="String" precision="Byte"
    type="DType.Int32" <!-- new -->
         scale="Byte" size="Integer"/>
```

Using [DBType](https://msdn.microsoft.com/en-us/library/system.data.dbtype%28v=vs.110%29.aspx)

Everything is now a string/varchar because `Layouts` return a `string`

Current code

``` csharp
  string stringValue = par.Layout.Render(logEvent);

  p.Value = stringValue;
  command.Parameters.Add(p);
```

**Comment by SergeyChanaev** [comment]
Waiting for this feature!
For some reason in case you use MS SQL and stored procedure -> date parameter will be passed correctly to the procedure. Same set up, but using PostgreSQL is complaining, that function (PostgreSQL analog of Stored Procedure) is expecting parameter of type "text" instead of type "timestamp without time zone" (PostgreSQL analog of DType.DateTime)

**Comment by 304NotModified** [comment]
This would be a nice feature, but other features have higher prio (e.g. structured logging). 

If someone likes to help with this feature, please let us know!

**Comment by damienbod** [comment]
Support for type Json would be great

**Comment by 304NotModified** [comment]
json to database? Is there a special DBType form from .NET?

**Comment by damienbod** [comment]
It would be great if the logs could be sent to a PostgreSQL NoSQL which requires a Json Type.

http://www.npgsql.org/doc/types/basic.html?q=json

The default target for this is string, but should be sent as a json type and not a text type.  It would be nice if this was possible using the database target. Otherwise I could always write a new target. 

?

 Greetings Damien

**Comment by 304NotModified** [comment]
I prefer extending the target. PR welcome ;)

**Comment by ObikeDev** [comment]
Added pull request #2767

**Comment by 304NotModified** [comment]
To do:

- [ ] Complete #2849
- [ ] get all the good ideas from https://github.com/NLog/NLog/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+label%3Adatabase-target+milestone%3A4.6+

**Comment by 304NotModified** [comment]
done, in NLog 4.6 RC
