### ISSUE TITLE
ILogger Extension Methods show up in the callsite

### ISSUE THREAD

**Issue by wadebaird** [NLog/NLog#5312]
If you implement your own ILogger Extension method, that method will show up as the callsite.

The AddHiddenAssembly doesn't work as the extension method is within the consuming assembly and we don't want to create a whole new assembly just for the one class.

We can't pass in the Type to the first method of the Log call as we interact with everything as an ILogger, so we don't have direct access to NLog.

**NLog version**: (e.g. 4.4.13)
5.2.3

 - Why do we need it?
 - There are several issues like this reported on Stackoverflow as well as other sites and no work around for them. Here is an example:
     - https://stackoverflow.com/questions/16366655/can-nlog-preserve-callsite-information-through-c-sharp-extension-methods

**Comment by snakefoot** [comment]
This issue is similar to #1145, where more control is wanted than to exclude the entire assembly. There are currently these work-arounds:
- Place your extension methods in an isolated assembly, and then add to hidden assemblies.
- Provide the extension-class-type as first parameter to `ILogger.Log(Type hiddenClassType, LogEventInfo logEvent)`.

My goal for NLog v6 is to extract all callsite-logic with StackTrace-scanning away from the NLog-core. This means removing `LogManager.AddHiddenAssembly` and all logic around it into extension-methods that lives in it own NLog.CallSite-nuget-package. See also #5245

I'm not planning to add any more public methods, that are about to be marked obsolete right after. But very interested in pull-request that can pave the road for making it easy to rip-out the callsite-logic from NLog-core. I don't mind the basic logic where it is possible to assign callsite-info on the LogEventInfo (ex. from caller-member-attributes), but all the stuff with StackTrace-scanning should be moved out with NLog v6.

**Comment by wadebaird** [comment]
Thank you for your feedback. As I mentioned in my comments, I can't use either of the workarounds unfortunately. 

I understand the desire to not add an api that will be obsoleted, but this is sorely needed and shouldn't add any more overhead when obsoleting AddHiddenAssembly.

Thank you.

**Comment by snakefoot** [comment]
Guess we are stuck then, until the callsite-registration-methods are implemented as extension-methods for the `LogManager.Setup()`-fluent-api

**Comment by wadebaird** [comment]
Thank you @snakefoot. Let me know if you need assistance on the next version.

**Comment by snakefoot** [comment]
[NLog v5.3.1](https://www.nuget.org/packages/NLog) has been released, that allows you to hide specific class-type, instead of the entire assembly.
