### ISSUE TITLE
Callsite Layout Renderer and Caller Attributes

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#532]
The current `CallSiteLayoutRenderer` uses the stacktrace for the method name, line number and file name.

This could be done with the [Caller attributes](https://msdn.microsoft.com/en-us/library/hh534540.aspx). In theory this would be a performance improvement. 

This should be tested in a prototype.

Keep in mind that the current classname isn's supported with the 'Caller Attributes'.

From a quick scan, this should be done:
- Extend **all** the methods in the `Logger` with the following parameters:

```
 [CallerMemberName] string memberName = "",   [CallerFilePath] string sourceFilePath = "",
        [CallerLineNumber] int sourceLineNumber = 0
```

Extend the `LogEventInfo` with the three properties so that the `CallSiteLayoutRenderer` could use this information. 

Inspired by #509

**Comment by sorin-bolos** [comment]
I gave the Caller attributes a try, using the approach sketched above. 

Even after obfuscating with .NET Reactor the method name, file name and line line number look ok, but the class name is still obfuscated because there is no attribute for that.

When using 
`layout="${longdate:universalTime=true} | ${uppercase:${level}} | ${callsite} -> ${message}"`
 I get:

*2015-03-08 03:16:41.5883 | ERROR | At09ooH3UChoDESHRc.OWt56Q4H8GFKUfs6n9.CallLogger -> my error log*

When using 
`Layout = "${longdate:universalTime=true} | ${uppercase:${level}} | ${callsite:className=false:fileName=true:includeSourcePath=false:methodName=false} -> ${message}" `
(like in  #509)

i get 

*2015-03-08 03:12:09.1576 | ERROR | (Program.cs:49) -> my error log*

**Comment by 304NotModified** [comment]
There is a problem with binary incompatibility with this. This will force users to convert ALL there code in one solution to NLog5 (if they move from NLog 4).

This is bad.

FYI:

if we have both in the interface, like

```c#
public interface ILogger2
{
  void Info(string message);
  void Info(string message, [CallerMemberName] string memberName = "");
}
```

Then the call to `Info("test")` will invoke the one without the caller attributes (also in .Net 4.5 / 4.6)

**Comment by snakefoot** [comment]
Partially resolved with #2386. Now the callsite-layout-renderer will attempt to use  Caller Attributes (when available)

Still missing the optimization of not capturing StackTrace when actually having the needed information from Caller-Attributes.

**Comment by snakefoot** [comment]
With PR  #3431 merged, then one just needs to implement some ILogger-extensions that makes it easier to capture Caller Attributes.

NLog 5.0 is now capable to use Caller Attributes using `LogEventInfo.SetCallerInfo`, instead of introducing the overhead of capturing StackTrace (and walking the stack).

**Comment by snakefoot** [comment]
@304NotModified Any opinion on how to implement better access to caller-attributes in NLog 5.0:

- Should it be new ILogger-interface with new extension-methods? (Removing all the old ILogger-interfaces)
```
interface ILogger
{
   bool IsEnabled(LogLevel level);

   void Log(Type wrapperType, LogEventInfo logEvent);

   void Log(LogLevel level, Exception exception, string message, params object[] args);

   void Log(LogLevel level, string message, params object[] args);
}
```

Where extension method looks like this (Will not allow unlimited string-format parameters):

```
        public void Info<T>(this ILogger logger, T value
            , LogWithOptionalParameterList _ = default(LogWithOptionalParameterList)
            , [CallerMemberName] string callerMemberName = "", [CallerFilePath] string callerFilePath = "", [CallerLineNumber] int callerLineNumber = 0)
        {
            if (logger.IsEnabled(LogLevel.Info))
            {
                var logEvent = LogEventInfo.Create(LogLevel.Info, Name, null, value);
                logEvent.SetCallerInfo(null, callerMemberName, callerFilePath, callerLineNumber);
                WriteToTargets(null, logEvent);
            }
        }
```

- Should it be moving LogBuilder out of Fluent-namespace and change into a struct?

`logger.Info().Log(ex, msg);`

Where `Info()` initializes LogBuilder with caller-attributes. Allowing "unlimited" format-parameters in the `Log()`-method.

**Comment by snakefoot** [comment]
Created PullRequest #4044 where Fluent.LogBuilder is made obsolete, and instead introduced `LogEventBuilder`  that skips allocations unless LogLevel is enabled.
