### ISSUE TITLE
Mail target is duplicated in website docs

### ISSUE THREAD

**Issue by jfontsaballs** [NLog/NLog#5376]
Mail target is duplicated in website docs. Both links link to the same webpage. It creates some confusion, as it may be understood that there are two different mail targets.

Please see screenshot:

![imatge](https://github.com/NLog/NLog/assets/25230616/511bea93-d527-47a9-8116-367264c8c804)

**Comment by snakefoot** [comment]
Yes it was confusing times when NetStandard1 and NetStandard2 was introduced, and SmtpClient was marked as obsolete by Microsoft.

The goal was that MailKit-Target should completely replace the original MailTarget (Since SmtpClient was marked obsolete), so it inherited the type-alias `mail`. Allowing users to move from .NET Framework to .NET Core without having to update their `NLog.config`-file (or maintain 2 files if they wanted to support both platforms).

Now with NLog v5 then it is possible to add multiple type-alias to a NLog Target, and now the MailKit-Target recognizes both `mail` and `mailkit. I have update the [config-page](https://nlog-project.org/config/) to say MailKit. But they both point to the same wiki-page, since they have identical options and behavior (Just using different email-clients underneath).

**Comment by snakefoot** [comment]
Closing issue as answered, due to inactivity.
