### ISSUE TITLE
Performance issue on NLog.Targets.FileArchiveModes.FileArchiveModeBase.GetExistingArchiveFiles(string)

### ISSUE THREAD

**Issue by czd890** [NLog/NLog#5393]
When there are tens of thousands of files in the directory, GetExistingArchiveFiles has serious performance problems.

https://github.com/NLog/NLog/blob/34c26bc02dd3026459228f1915ca27f93b46a0d0/src/NLog/Targets/FileArchiveModes/FileArchiveModeBase.cs#L102-L104

**NLog version**: 5.2.3+a5ddef92a8afb22508450803e37c001f4a3ba52a
**Platform**: .Net6/ARM64b 
**Current NLog config** (xml or C#, if relevant)
```json
{
    "NLog": {
        "targets": {
            "async": true,
            "local-file": {
                "type": "File",
                "fileName": "/log/logs.log",
                "keepFileOpen": true,
                "concurrentWrites": true,
                "archiveAboveSize": 10485760,
                "archiveEvery": "Day",
                "archiveNumbering": "DateAndSequence",
                "archiveDateFormat": "yyyyMMddHHmm",
                "maxArchiveDays": 30,
                "enableArchiveFileCompression": true,
                "archiveFileName": "/logs/logs.{#}.zip"
            }
        }
    }
}
```
### dotnet-trace -p *** -o *** --duration 00:02:00
![1698730604300](https://github.com/NLog/NLog/assets/4011549/4df13735-5bfb-4d27-bd63-9f4f09a2ba01)

### dotnet-dump(dumpheap -stat)

MT | Count | TotalSize | Class Name
-- | -- | -- | --
ffff3cb3ad38 | 43 | 2,752 | System.Func<NLog.Targets.Target>
ffff3cf1d990 | 52 | 2,496 | NLog.Extensions.Logging.NLogLogger
ffff3c158078 | 56 | 4,032 | NLog.Logger
ffff3c9fd520 | 57 | 4,560 | NLog.Internal.TargetWithFilterChain[]
ffff3cb18f88 | 148 | 9,472 | NLog.Config.Factory<NLog.LayoutRenderers.LayoutRenderer,   NLog.LayoutRenderers.LayoutRendererAttribute>+GetTypeDelegate
ffff3cb19070 | 165 | 10,560 | System.Func<NLog.LayoutRenderers.LayoutRenderer>
ffff3c9fd490 | 663 | 37,128 | NLog.Internal.TargetWithFilterChain
ffff3ca12148 | 12,004 | 1,440,480 | NLog.LogEventInfo
ffff3d05b268 | 134,795 | 6,470,160 | NLog.Targets.DateAndSequenceArchive
ffff3a16bbd0 | 134,796 | 25,880,832 | System.IO.FileInfo

**Comment by snakefoot** [comment]
What kind of performance issues are you experiencing ?

Notice the callstack you have captured is from the async-background-thread doing file-archive-clenaup., so it should not affect the behavior of the application-threads.

Maybe try and enable the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) (If possible `"internalLogLevel": "Debug"`. Then it might reveal what is happening inside NLog.

Maybe the FileSystem is returning funky File-TimeStamps, because not support file-birthtime-time. Thus causing NLog to frequently perform file-archive-operation and file-archive-cleanup.

Instead of using the NLog FIleTarget for file-archive-cleanup, then you could also setup a cron-job / scheduled-task for daily cleanup.

**Comment by snakefoot** [comment]
Closing issue, due to inactivity.
