### ISSUE TITLE
Google AV is blocking NLog.dll and reporting it is infected with a Virus.

### ISSUE THREAD

**Issue by BackTrak** [NLog/NLog#5457]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: 5.11 and up

**Platform**: .Net 4.7.2

**Current NLog config** (xml or C#, if relevant)

```xml
N/A
```

- What is the current result?

Take any .Net full framework version of NLog.dll from 5.11 and up and upload it to Google Drive. Then try to download it. Google blocks the download and informs you that the executable is infected with a virus. 

- What is the expected result?

Google should not detect a virus.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

N/A

- Please post full exception details (message, stacktrace, inner exceptions)

N/A

- Are there any workarounds? yes/no

No

- Is there a version in which it did work? 

NLog versions 4.7.15 and lower do not appear to have the issue.

- Can you help us by writing an unit test?

N/A

**Comment by BackTrak** [comment]
Scanning NLog.dll with VirusTotal also shows that Google doesn't like the latest version. No indication on why not.

**Comment by snakefoot** [comment]
I'm guessing it is false positive, but I'm not the owner of Google / ClamAV.

See also: 

- https://www.reddit.com/r/radarr/comments/18v0ey2/clam_av_tripped_on_the_latest_linuxserverio/
- https://www.reddit.com/r/qnap/comments/18vk0j5/antivirus_false_positive/

You can try and contact Google / ClamAV and report false-positive for re-verification:

- https://www.clamav.net/contact

**Comment by BackTrak** [comment]
It is most likely a false positive, but it is for sure blocking download of any zip file from Google that contains a current version of NLog.dll. Because this library is used by everyone, the impact will be wide.

**Comment by snakefoot** [comment]
Can only agree it is most unfortunate, but it seems out of my control.



Sent from my Galaxy



-------- Original message --------
From: Nick Pirocanac ***@***.***>
Date: 06/01/2024 00:03 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog] Google AV is blocking NLog.dll and reporting it is infected with a Virus. (Issue #5457)


It is most likely a false positive, but it is for sure blocking download of any zip file from Google that contains a current version of NLog.dll. Because this library is used by everyone, the impact will be wide.

**Comment by snakefoot** [comment]
Looks like issue has been resolved with latest release:

- https://lists.clamav.net/pipermail/clamav-virusdb/2024-January/008529.html

> Dropped Detection Signatures:
> - Win.Packed.Msilheracles-10017861-0

**Comment by snakefoot** [comment]
Closing issue as resolved
