### ISSUE TITLE
LoadConfigurationFromAppSettings() in NLog.Extensions.Hosting

### ISSUE THREAD

**Issue by alexeygritsenko** [NLog/NLog#5477]
Hi, im upgrading from version 4 to 5. As far as I understand, you have different packages
- NLog.Web.AspNetCore for websites
- NLog.Extensions.Hosting for worker services
- NLog.Extensions.Logging for any other applications

I have worker service, it vs template contain appsettings.json like ASP.NET template. Why NLog provides a method LoadConfigurationFromAppSettings() only for NLog.Web.AspNetCore? Isn't this relevant for NLog.Extensions.Hosting? I came across the fact that this method is also needed here since the configuration format is no different.

**Comment by snakefoot** [comment]
Yes that is pretty much the purpose of the different nuget-packages. `NLog.Extensions.Logging` + `NLog.Extensions.Hosting` tries to be slim wrappers that only registers NLog as logging-provider.

The `LoadConfigurationFromAppSettings` is included with `NLog.Web.AspNetCore` because it has all the dependencies included upfront for loading configuration from appsettings.json-file. Allowing it to manually load configuration before the host-builder is ready.

The `LoadConfigurationFromAppSettings` is best-effort and not very optimal way of loading the NLog-configuration. It just probes lots of different places for a possible NLog-configuration, which is then loaded. It kind of ressembles how NLog autoloads its `Nlog.config`-file.

The goal is that one just uses `AddNLog` or `UseNLog` for setting up NLog as logging-provider, and those methods will automatically load the NLog-configuration from the host-configuration (if available).

**Comment by alexeygritsenko** [comment]
Thank you. Then could you comment on two points from the example I noted on the screenshot? Here I am trying to understand the different configuration going on in two places. Or does the configuration take place in 1 place, and then it will be used in 2? Will the way 1 place is configured affect 2 or are they unrelated?
![image](https://github.com/NLog/NLog/assets/10233486/5208291a-756e-446b-bd2c-39001d0fcfb9)

**Comment by snakefoot** [comment]
The only reason for the premature `LoadConfigurationFromAppSettings` is for doing early logging (Like `logger.Debug("Init main")`) before `Host.CreateDefaultBuilder()`. 

But `UseNLog()` / `AddNLog()` by itself is enough for setting up NLog as Logging Provider.

**Comment by alexeygritsenko** [comment]
Thanks!
