### ISSUE TITLE
Archive files are never created when there are lot of write in log file

### ISSUE THREAD

**Issue by jforestier** [NLog/NLog#550]
When i write informations in logfile with interval of 10ms, the archive files are never created.

I've configure my nlog to archive every minute. So, 1 archive for each minute.
If i write with 100ms interval no problem.

I've test this for 20 minutes with 10ms and 100ms interval.

Below informations of my configuration :

ArchiveEvery = FileArchivePeriod.Minute;
ArchiveFileName = Path.Combine(logDirectory, ArchiveLogFilename);
ArchiveNumbering = ArchiveNumberingMode.Date;
ArchiveDateFormat = "yyyy-MM-dd hh-mm";
MaxArchiveFiles = 90;
KeepFileOpen = false;
Encoding = System.Text.Encoding.UTF8;

**Comment by Xharze** [comment]
@jforestier Could you provide a sample project for this issue?

**Comment by ilya-g** [comment]
NLog relies on file last write time to determine whether it should archive the file: if the logEvent's timestamp is from next period (i.e. minute) and file last write time is from previous period, it decides to archive file.

Technically, it is possible that a file write begin in one period and might have completed in next period. In this case NLog, writing event from the next period, would not catch the difference between event's timestamp and last write time, and, as a consequence, would not archive file.

**Comment by 304NotModified** [comment]
@ilya-g do you think that we can fix this?

**Comment by madsmg** [comment]
We have been experiencing this issue quite a lot (log writes that overlaps into the next period), resulting in missed archiving. Currently we have implemented a workaround using a custom target.

One possible solution (however I have a hard time predicting all the consequences) could be to call File.SetCreationTimeUtc when creating the filestream in the base appender (to ensure that the creation time is reliable), and instead of LastWriteTimeUtc, use the CreationTimeUtc to determine when it is time for archival.

I am a complete newcomer in the open source world, but if you think the outlined solution is valid I would be happy to create a pull request.

**Comment by 304NotModified** [comment]
That's sounds like a good idea! I think it would be great if we can fix this issue! 

PR is accepted on this one.  If you need some insight info, just let us know!
