### ISSUE TITLE
I can't delete the generated log files

### ISSUE THREAD

**Issue by asleeguilez** [NLog/NLog#5657]
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: (5.3.12)

**Platform**:  .NET8

**Current NLog config** (C#, if relevant)

```json
"NLog": {
	"autoReload": true,
        "throwConfigExceptions": true,
        "internalLogLevel": "Info",
        "internalLogFile": "${basedir}/Logs/internal-nlog.txt",
        "targets": {
                "async": true,
                "apiColibri": {
                "type": "File",
                "fileName": "${basedir}/Logs/ApiColibri-${shortdate}.log",
                "maxArchiveFiles": 10
         },

```

The logs are generated correctly but when I try to delete log-file it remains in the directory and does not disappear until I stop application.
![image](https://github.com/user-attachments/assets/d0d1d6d6-1d3f-487b-8d28-78b3830a47e0)
And there is one file left that I can't open or delete.

Why does this behavior occur?

**Comment by snakefoot** [comment]
I'm guessing that is how the Windows operating system works. When deleting a file, then it will disappear from Windows Explorer, but until all file-handles has been closed, then it cannot be fully deleted.

NLog FileTarget checks if file has been deleted, before writing to the file (throttled so only checking every 1 sec). If NLog FileTarget detects the file has been deleted, then it closes the file-handle.

But if there is no output to the NLog FileTarget, then it will not perform any checking if file has been deleted, and not close the file-handle (until application is closed).

Not sure what you mean with "And there is one file left that I can't open or delete." Since there are lots of unit-tests that verify that one can delete files, even though still opened by NLog FileTarget. Maybe you have some other background application like AntiVirus/Windows-Defender that is blocking?

**Comment by snakefoot** [comment]
One can configure the NLog FileTarget to periodically release its filehandles. Using [openFileCacheTimeout](https://github.com/NLog/NLog/wiki/File-target) to close file-handles every 60 secs:
```json
        "apiColibri": {
                "type": "File",
                "fileName": "${basedir}/Logs/ApiColibri-${shortdate}.log",
                "maxArchiveFiles": 10,
                "openFileCacheTimeout": 60
         },
```
Or using using [KeepFileOpen](https://github.com/NLog/NLog/wiki/File-target) to close file-handles after each file-write (heavy performance hit):
```json
        "apiColibri": {
                "type": "File",
                "fileName": "${basedir}/Logs/ApiColibri-${shortdate}.log",
                "maxArchiveFiles": 10,
                "keepFileOpen": false
         },
```
