### ISSUE TITLE
When <include>ing a file with a <nlog> root element, autoReload in parent config is ignored

### ISSUE THREAD

**Issue by stylpe** [NLog/NLog#668]
Discovered for version 3.1. Apologize for not having time to test newer versions, we're getting a release ready :P
Small (untested) example to illustrate:
NLog.config:
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  autoReload="true" internalLogToConsoleError="true">
  <include file="include.config" />
</nlog>
```
include.config:
```xml
    <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    </nlog>
```

AutoReload will not be enabled.

Adding autoReload="true" to include.config enables autoReload for both files (which corresponds to documented behaviour).

**Comment by 304NotModified** [comment]
Thanks for the submit. But it doesn't seem a bug? If the attribute is only at nlog.config, changes of include.config should not trigger an auto reload

**Comment by stylpe** [comment]
Oh, right, clarification: Neither file is registered for auto reload. The attribute in include.config controls the behaviour of both files. That seems backwards.

**Comment by stylpe** [comment]
Or more specifically, even the absence of the attribute in include.config prevents the main config from auto reloading.

**Comment by 304NotModified** [comment]
Backward=awkward? 

PS: success with the release

**Comment by stylpe** [comment]
Well, one consequence is that in order to enable auto reload at all, the last loaded file has to have the attribute set to true. I expected that if the attribute was not set, the current setting would not change, but I'm guessing it deserializes to its default value of false and consequently overrides the parent config.

I guess it just surprised me when auto reload stopped working when I added the include. If you opt to not change the behaviour, at least clarify this in the documentation as a gotcha.

**Comment by stylpe** [comment]
Oh, also, this problem does not exist with other attributes on the nlog element, at least not internalLogToConsoleError (setting it to true in the master config and unset in the include, and it is still enabled).

**Comment by 304NotModified** [comment]
Thanks for the explanation. This is probably not fixed in 3.2. 

Maybe we have time to fix it in 4.0.

**Comment by 304NotModified** [comment]
PR would be accepted of course

**Comment by tetrodoxin** [comment]
So, to sum it up: The expected behavior is sort of bottom-up? 'autoReload' in included Files refresh the parent too, but autoReload in parent only observes the parent file, not the included?

**Comment by 304NotModified** [comment]
Good question! 

I think it should be top down, eg, the parent pushes to the children.  That's also the case with config files is IIS

**Comment by tetrodoxin** [comment]
Seems straightforward to me too. An inheritance like behavior.  
If no one gets there first,  I'll take charge of it.

**Comment by 304NotModified** [comment]
No one is working on it, so that would be great! :+1:

**Comment by 304NotModified** [comment]
PS this one is related: https://github.com/NLog/NLog/issues/298

**Comment by bhaeussermann** [comment]
I'm currently looking into this, and I've started by writing some unit tests expressing the expected behaviour (I could not find any existing tests that test auto-reloading).

So my understanding of the expected behaviour is as follows:
1) We shall monitor config files for changes based on whether the `autoReload` option applies to the particular config file. That is, monitor only those files where `autoReload` is `true` for that file.
2) When a change is detected in any config file which is monitored (based on (1) ), then we reload the entire configuration (starting at the root config).
3) The root config's default for `autoReload` is `false`.
4) Each included config's default for `autoReload` is the value of `autoReload` in its parent.

For example, if main.config specifies `autoReload = true`, and include.config does not specify a value for `autoReload`, then both files will be monitored for changes.  
If main.config does not specify `autoReload`, but include.config specifies `autoReload = true`, then we will monitor only include.config for changes. 

Does this sound correct?

**Comment by 304NotModified** [comment]
That sounds correct. Unit tests for this are in https://github.com/NLog/NLog/blob/fa167e3e4c3d7cb7dfac49d018049bd3f69c780c/tests/NLog.UnitTests/LogFactoryTests.cs#L215

**Comment by bhaeussermann** [comment]
> Unit tests for this are in https://github.com/NLog/NLog/blob/fa167e3e4c3d7cb7dfac49d018049bd3f69c780c/tests/NLog.UnitTests/LogFactoryTests.cs#L215

Well, that explains why I didn't find them :P

**Comment by bhaeussermann** [comment]
There will be many auto-reload tests, so I think I'll put them into their own test class.

**Comment by 304NotModified** [comment]
That's OK :)  it would be nice if there were easier to find
