### ISSUE TITLE
How to register async target programmatically?

### ISSUE THREAD

**Issue by migig** [NLog/NLog#685]
I'm trying to register a custom *async* target and associated rule, [programmatically](https://github.com/nlog/nlog/wiki/Configuration-API).

When do I reference the `target` and when do I reference the async `wrapper`?

````c#
var target = new MyCustomTarget();
var wrapper = new AsyncTargetWrapper(target, 5000, AsyncTargetWrapperOverflowAction.Discard);
    
var rule = new LoggingRule("*", LogLevel.Trace, target); // use "target" or "wrapper" here?
    
LogManager.Configuration.AddTarget("foo", wrapper);      // use "target" or "wrapper" here?
LogManager.Configuration.LoggingRules.Add(rule);
    
LogManager.ReconfigExistingLoggers();
````

**Comment by 304NotModified** [comment]
You code example should work. So, addTarget with the Wrapper and addRule with the target.

**Comment by Xharze** [comment]
@migig Have your question been answered?

**Comment by migig** [comment]
@Xharze @304NotModified What is the implication of addingRule with wrapper instead of target?

So use wrapper in both calls.

I ask because it works both ways, but I'm worried it will lead to problems?

**Comment by Xharze** [comment]
You should use the wrapper. The reason is that the asynchronous features are implemented in the wrapper not the target. If you pass in the target, you'll effectively bypass the asynchronous features of the wrapper. Both `AddRule` and `AddTarget` must use the wrapper.
The reason the rule must use the wrapper is that, when a logevent matches this rule it should be written to the wrapper.
The reason the target must use the wrapper is basically the same.

**Comment by migig** [comment]
@Xharze Thanks that makes sense! :smile:

**Comment by pedramkh8** [comment]
when you are adding instantiate rule you should pass wrapper instead of target.
