### ISSUE TITLE
NLog 3.2.1 does not work with two (inner\outer) log wrappers

### ISSUE THREAD

**Issue by AceHack** [NLog/NLog#696]
If you write a log wrapper and give it the correct declaring type it works fine as long as there is only one wrapper. If you have two wrappers it stops at the first one even if you give it a declaring type of the second one. This does not happen on v3.1.0.0. Please fix.

```xml
<target name="console" type="Console"
    layout="${callsite:className=True:fileName=False:includeSourcePath=False:methodName=True} ${message}" />
```
```csharp
class InnerLoggerWrapper
{
    public Type BoundaryType { get; set; }
    private readonly Logger _logger;

    public InnerLoggerWrapper(string name)
    {
        BoundaryType = typeof (InnerLoggerWrapper);
        _logger = LogManager.GetLogger(name);
    }

    public void Log(string message)
    {
        _logger.Log(BoundaryType, new LogEventInfo(LogLevel.Debug, _logger.Name, message));
    }
}
class OuterLoggerWrapper
{
    private readonly InnerLoggerWrapper _inner;

    public OuterLoggerWrapper(string name)
    {
        _inner = new InnerLoggerWrapper(name) {BoundaryType = typeof (OuterLoggerWrapper)};
    }

    public void Log(string message)
    {
        _inner.Log(message);
    }
}
class Program
{
    static void Main(string[] args)
    {
        var l = new OuterLoggerWrapper("test");
        l.Log("test");
        Console.ReadKey(true);
    }
}
```

This output's "ConsoleApplication1.Program.Main test" with nlog version 3.1 which is correct.

This output's "ConsoleApplication1.InnerLoggerWrapper.Log test" with nlog version 3.2.1 which is wrong.

**Comment by 304NotModified** [comment]
copy of #662 .

Is this #579?

**Comment by AceHack** [comment]
I will let you know if 3.2.1 fixes the issue once it's released on nuget.   Thanks.

**Comment by AceHack** [comment]
I just tested with nlog 3.2.1 from nuget and the issue still occurs.  This is still an open issue.

**Comment by 304NotModified** [comment]
OK, thanks for testing.

**Comment by Xharze** [comment]
@AceHack I've looked into this. As far as I can see this was removed because it introduced some other issues with the callsitelayoutrenderer. The problem with fixing this, is that we have know way of knowing what the user expects.
A workaround could be defining a the callsitelayoutrenderer with skipFrames to match your use case. See https://github.com/NLog/NLog/wiki/Callsite-layout-renderer. The documentation for the layout renderer was out-of-date, and missing the skipFrames property.
If you can provide us with a solution not breaking any of the other features i the callsitelayoutrenderer please let us know, as this would be a great feature. Until then I'll mark this as wontfix, and close the issue, please reopen if needed

**Comment by 304NotModified** [comment]
> As far as I can see this was removed because it introduced some other issues with the callsitelayoutrenderer.
Do you know which issue?

**Comment by Xharze** [comment]
@304NotModified I'll see if I can find the issue

**Comment by bj0** [comment]
Note that this also breaks the case where your logging wrapper uses extension methods: https://stackoverflow.com/questions/16366655/can-nlog-preserve-callsite-information-through-c-sharp-extension-methods

Someone suggested AddHiddenAssembly, which appears to ignore everything in that assembly.  Is there anything similar for adding a subset of classes (instead of the whole assembly) to ignore?  This would be useful for ignoring extension classes.

**Comment by 304NotModified** [comment]
This isn't possible yet.  The skipframes won't help in this case I think? 

If you like this new feature,  please open a new issue. Thanks!

**Comment by bj0** [comment]
I see.  I tried differen't values of skipFrames but it didn't seem to change anything in my log output.  I can open another issue, but I'm not really sure it would be much different than this one as I don't know the best way to address this.  Someone in that thread suggested making ```.Log()``` take multiple types instead of just one (they might be working on a PR).

**Comment by 304NotModified** [comment]
Did you test with nlog 4?

**Comment by bj0** [comment]
I tried 3.2.1 and 4.0 with ```${callsite:skipFrames=1}```, also with ```=2``` and ```=3```.  I couldn't tell any difference in the output.

**Comment by kabua** [comment]
What if we added a skipFrames param to the LogEventInfo, that way we can control it from the LogExtension - the source of the issue. In my case we only have a few log extension wrapper methods and the rest use the stand methods.

**Comment by snakefoot** [comment]
@kabua Please create new issue instead of waking old giants. See also: https://github.com/NLog/NLog/wiki/Custom-extension-of-Logger-interface#custom-wrapper-and-callsite
