### ISSUE TITLE
PostFilteringWrapper  with filter on threadid

### ISSUE THREAD

**Issue by mdissel** [NLog/NLog#727]
Is it possible to use a PostFilteringWrapper in combination with a filter on the threadid equals threadid from the exception?
I want to create an email target that will send an email when an exception is logged and it should contain the buffered log messages from all levels from the same threadid

**Comment by 304NotModified** [comment]
@Xharze do you know this?

**Comment by 304NotModified** [comment]
This should be possible. I think you need the [Event properties](https://github.com/NLog/NLog/wiki/EventProperties-Layout-Renderer) because the exception doesn't have the property "threadid"

In the condition you can use both `${threadid}` and `${event-properties}`

But I'm not sure, aren't those always the same? An if they aren't, I think you will lose messages.

**Comment by Xharze** [comment]
@mdissel Has you question been answered?

**Comment by 304NotModified** [comment]
We will assume your question has been answered. If not, let us know.
