### ISSUE TITLE
Network target cache

### ISSUE THREAD

**Issue by Hackthor** [NLog/NLog#777]
Hello,
we are using NLog for logging into file etc. Now we want to use "network target" on the same project. But I couldn't find anything about caching with this target. When I start network logging and logger project is not started yet (I mean TCP server is offline), it is possible to run out of memory because of caching messages for network target? We don't want our customer to be angry :) Thank you for your response.

**Comment by 304NotModified** [comment]
Hi, 

Nothing get cached. When it isn't running,  you get connection errors. I would recommend to (temporary)  turn off logging to the network target if the server is offline.

**Comment by 304NotModified** [comment]
I will amuse your question has been answered. If not, let me know!

**Comment by snakefoot** [comment]
[NLog 2.1](https://github.com/NLog/NLog/issues/88) Introduced the `MaxQueueSize`-option that prevents ever growing memory-usage when `KeepConnection = true`.

[NLog 4.2.1](https://github.com/NLog/NLog/pull/1031) Introduced the `MaxConnections`-options that prevents ever growing memory-usage when `KeepConnection = false`

[NLog 5.0](https://github.com/NLog/NLog/pull/4542) changes NetworkTarget to have the limits enabled by default with discard-behavior, instead of memory-usage continue growing.
