### ISSUE TITLE
Support object values for MDLC

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#883]
Like https://github.com/NLog/NLog/pull/743 

for

https://github.com/NLog/NLog/pull/833

**Comment by BrutalCode** [comment]
@304NotModified I completed it. Do you want to pull request?

**Comment by 304NotModified** [comment]
PR is always good :)

**Comment by 304NotModified** [comment]
PR merged!

**Comment by BrutalCode** [comment]
Thank you! What is the right time to update MDLC wiki page for this update?

**Comment by 304NotModified** [comment]
before release I think.

**Comment by UgurAldanmaz** [comment]
Should we remove the 'needs document on wiki' label as it documented?

**Comment by 304NotModified** [comment]
That's possible. But I ignore those labels on closed issues. 

Do you think it's better to remove it?

**Comment by UgurAldanmaz** [comment]
Not sure.

It seems that it is a reminder to document, so it should be removed when complete the documentation task for clarity of next search result.

It also seems that it is a step to close the issue. Such as: You should not close unless to complete the documentation. Otherwise you may forget to document it.

Also it seems that this discussion is trivial thing :) Forget.
